# Generated by Django 5.2 on 2026-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsBoxScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2015-16', '2015-16'), ('2016-17', '2016-17'), ('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26')], db_index=True, max_length=10, verbose_name='Temporada')),
                ('season_type', models.CharField(choices=[('pre-season', 'Pre-Temporada'), ('regular-season', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('all-star', 'All-Star'), ('playin', 'Play-In'), ('ist', 'IST')], db_index=True, max_length=20, verbose_name='Tipo de Temporada')),
                ('team_abb', models.CharField(db_index=True, max_length=20, verbose_name='Equipo')),
                ('game_id', models.CharField(db_index=True, max_length=20, verbose_name='ID del Partido')),
                ('matchup', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enfrentamiento')),
                ('home_away', models.CharField(blank=True, max_length=10, null=True, verbose_name='Local/Visitante')),
                ('gdate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fecha del Juego')),
                ('wl', models.CharField(blank=True, max_length=1, null=True, verbose_name='Resultado')),
                ('min', models.IntegerField(blank=True, default=0, null=True, verbose_name='Minutos')),
                ('pts', models.IntegerField(blank=True, default=0, null=True)),
                ('fgm', models.IntegerField(blank=True, default=0, null=True)),
                ('fga', models.IntegerField(blank=True, default=0, null=True)),
                ('fg_pct', models.FloatField(blank=True, default=0.0, null=True)),
                ('fg3m', models.IntegerField(blank=True, default=0, null=True)),
                ('fg3a', models.IntegerField(blank=True, default=0, null=True)),
                ('fg3_pct', models.FloatField(blank=True, default=0.0, null=True)),
                ('ftm', models.IntegerField(blank=True, default=0, null=True)),
                ('fta', models.IntegerField(blank=True, default=0, null=True)),
                ('ft_pct', models.FloatField(blank=True, default=0.0, null=True)),
                ('oreb', models.IntegerField(blank=True, default=0, null=True)),
                ('dreb', models.IntegerField(blank=True, default=0, null=True)),
                ('reb', models.IntegerField(blank=True, default=0, null=True)),
                ('ast', models.IntegerField(blank=True, default=0, null=True)),
                ('stl', models.IntegerField(blank=True, default=0, null=True)),
                ('blk', models.IntegerField(blank=True, default=0, null=True)),
                ('tov', models.IntegerField(blank=True, default=0, null=True)),
                ('pf', models.IntegerField(blank=True, default=0, null=True)),
                ('plus_minus', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'verbose_name': 'Teams Box Scores',
                'verbose_name_plural': 'Teams Box Scores',
                'indexes': [models.Index(fields=['season', 'season_type'], name='teams_teams_season_365092_idx'), models.Index(fields=['team_abb'], name='teams_teams_team_ab_c281f7_idx'), models.Index(fields=['game_id'], name='teams_teams_game_id_307f00_idx')],
                'unique_together': {('season', 'season_type', 'team_abb', 'game_id')},
            },
        ),
    ]
