# Alter team_abb to max_length=50 and null=True for CSV values like "West NBA All Stars West"

from django.db import migrations, models


def get_team_abb_field():
    return models.CharField(
        max_length=50,
        verbose_name="Equipo",
        db_index=True,
        null=True,
        blank=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_teamsboxscores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamsgeneraltraditional",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneraladvanced",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneralfourfactors",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneralmisc",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneralscoring",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneralopponent",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneraldefense",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneralviolations",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsgeneralestimatedadvanced",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsclutchtraditional",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsclutchadvanced",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsclutchfourfactors",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsclutchmisc",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsclutchscoring",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsclutchopponent",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsboxouts",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamshustle",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypeballhandler",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypecut",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypehandoff",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypeisolation",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypemisc",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypeoffscreen",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypepostup",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypeputbacks",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytyperollman",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypespotup",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsplaytypetransition",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingcatchshoot",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingdefensiveimpact",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingdefensiverebounding",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingdrives",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingelbowtouch",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingoffensiverebounding",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingpainttouch",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingpassing",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingpostups",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingpullup",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingrebounding",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingshootingefficiency",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingspeeddistance",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamstrackingtouches",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsdefensedashboardoverall",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsdefensedashboard2pt",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsdefensedashboard3pt",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsdefensedashboardlt6",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsdefensedashboardlt10",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsdefensedashboardgt15",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsshotdashboardgeneral",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsshotdashboardshotclock",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsshotdashboarddribbles",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsshotdashboardtouchtime",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsshotdashboardclosestdefender",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsshotdashboardclosestdefender10",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsshooting",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsopponentshootingoverall",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsopponentshotsgeneral",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsopponentshotsshotclock",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsopponentshotsdribbles",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsopponentshotstouchtime",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsopponentshotsclosestdefender",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsopponentshotsclosestdefender10",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsadvancedboxscores",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsadvancedboxscoresadvanced",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsadvancedboxscoresfourfactors",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsadvancedboxscoresmisc",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsadvancedboxscoresscoring",
            name="team_abb",
            field=get_team_abb_field(),
        ),
        migrations.AlterField(
            model_name="teamsboxscores",
            name="team_abb",
            field=get_team_abb_field(),
        ),
    ]
