from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_team_abb_max_length_50"),
    ]
    operations = [
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS teams_teamsgeneralfourfactors; "
                "DROP TABLE IF EXISTS teams_teamsgeneralmisc; "
                "DROP TABLE IF EXISTS teams_teamsgeneralscoring; "
                "DROP TABLE IF EXISTS teams_teamsgeneralopponent; "
                "DROP TABLE IF EXISTS teams_teamsgeneraldefense; "
                "DROP TABLE IF EXISTS teams_teamsgeneralviolations; "
                "DROP TABLE IF EXISTS teams_teamsgeneralestimatedadvanced; "
                "DROP TABLE IF EXISTS teams_teamsclutchtraditional; "
                "DROP TABLE IF EXISTS teams_teamsclutchadvanced; "
                "DROP TABLE IF EXISTS teams_teamsclutchfourfactors; "
                "DROP TABLE IF EXISTS teams_teamsclutchmisc; "
                "DROP TABLE IF EXISTS teams_teamsclutchscoring; "
                "DROP TABLE IF EXISTS teams_teamsclutchopponent; "
                "DROP TABLE IF EXISTS teams_teamsplaytypeisolation; "
                "DROP TABLE IF EXISTS teams_teamsplaytypetransition; "
                "DROP TABLE IF EXISTS teams_teamsplaytypeballhandler; "
                "DROP TABLE IF EXISTS teams_teamsplaytyperollman; "
                "DROP TABLE IF EXISTS teams_teamsplaytypepostup; "
                "DROP TABLE IF EXISTS teams_teamsplaytypespotup; "
                "DROP TABLE IF EXISTS teams_teamsplaytypehandoff; "
                "DROP TABLE IF EXISTS teams_teamsplaytypecut; "
                "DROP TABLE IF EXISTS teams_teamsplaytypeoffscreen; "
                "DROP TABLE IF EXISTS teams_teamsplaytypeputbacks; "
                "DROP TABLE IF EXISTS teams_teamsplaytypemisc; "
                "DROP TABLE IF EXISTS teams_teamstrackingdrives; "
                "DROP TABLE IF EXISTS teams_teamstrackingdefensiveimpact; "
                "DROP TABLE IF EXISTS teams_teamstrackingcatchshoot; "
                "DROP TABLE IF EXISTS teams_teamstrackingpassing; "
                "DROP TABLE IF EXISTS teams_teamstrackingtouches; "
                "DROP TABLE IF EXISTS teams_teamstrackingpullup; "
                "DROP TABLE IF EXISTS teams_teamstrackingrebounding; "
                "DROP TABLE IF EXISTS teams_teamstrackingoffensiverebounding; "
                "DROP TABLE IF EXISTS teams_teamstrackingdefensiverebounding; "
                "DROP TABLE IF EXISTS teams_teamstrackingshootingefficiency; "
                "DROP TABLE IF EXISTS teams_teamstrackingspeeddistance; "
                "DROP TABLE IF EXISTS teams_teamstrackingelbowtouch; "
                "DROP TABLE IF EXISTS teams_teamstrackingpostups; "
                "DROP TABLE IF EXISTS teams_teamstrackingpainttouch; "
                "DROP TABLE IF EXISTS teams_teamsdefensedashboardoverall; "
                "DROP TABLE IF EXISTS teams_teamsdefensedashboard3pt; "
                "DROP TABLE IF EXISTS teams_teamsdefensedashboard2pt; "
                "DROP TABLE IF EXISTS teams_teamsdefensedashboardlt6; "
                "DROP TABLE IF EXISTS teams_teamsdefensedashboardlt10; "
                "DROP TABLE IF EXISTS teams_teamsdefensedashboardgt15; "
                "DROP TABLE IF EXISTS teams_teamsshotdashboardgeneral; "
                "DROP TABLE IF EXISTS teams_teamsshotdashboardshotclock; "
                "DROP TABLE IF EXISTS teams_teamsshotdashboarddribbles; "
                "DROP TABLE IF EXISTS teams_teamsshotdashboardtouchtime; "
                "DROP TABLE IF EXISTS teams_teamsshotdashboardclosestdefender; "
                "DROP TABLE IF EXISTS teams_teamsshotdashboardclosestdefender10; "
                "DROP TABLE IF EXISTS teams_teamsadvancedboxscores; "
                "DROP TABLE IF EXISTS teams_teamsadvancedboxscoresadvanced; "
                "DROP TABLE IF EXISTS teams_teamsadvancedboxscoresfourfactors; "
                "DROP TABLE IF EXISTS teams_teamsadvancedboxscoresmisc; "
                "DROP TABLE IF EXISTS teams_teamsadvancedboxscoresscoring; "
                "DROP TABLE IF EXISTS teams_teamsshooting; "
                "DROP TABLE IF EXISTS teams_teamsopponentshootingoverall; "
                "DROP TABLE IF EXISTS teams_teamsopponentshotsgeneral; "
                "DROP TABLE IF EXISTS teams_teamsopponentshootshotclock; "
                "DROP TABLE IF EXISTS teams_teamsopponentshotsdribbles; "
                "DROP TABLE IF EXISTS teams_teamsopponentshootstouchtime; "
                "DROP TABLE IF EXISTS teams_teamsopponentshotsclosestdefender; "
                "DROP TABLE IF EXISTS teams_teamsopponentshotsclosestdefender10; "
                "DROP TABLE IF EXISTS teams_teamshustle; "
                "DROP TABLE IF EXISTS teams_teamsboxouts; "
                "DROP TABLE IF EXISTS teams_teamsboxscores;"
            ),
            reverse_sql="",
        ),
    ]
