# Generated by Django 5.2.13 on 2026-04-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID del partido')),
                ('league', models.CharField(db_index=True, default='NBA', max_length=20, verbose_name='Liga')),
                ('season', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Temporada')),
                ('season_type', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Tipo de temporada')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha del partido')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Puntos local')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Puntos visitante')),
                ('n_result', models.CharField(blank=True, max_length=40, verbose_name='Resultado (ej. 110-98)')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-date', 'game_id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID del equipo')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Nombre (opcional)')),
                ('abbreviation', models.CharField(blank=True, max_length=10, verbose_name='Abreviatura')),
                ('conference', models.CharField(blank=True, max_length=10, verbose_name='Conferencia')),
                ('division', models.CharField(blank=True, max_length=30, verbose_name='División')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameMetadata',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='core.game')),
                ('starters_json', models.JSONField(blank=True, default=dict, verbose_name='Starters [{player_id, name, team, position}]')),
                ('arena', models.CharField(blank=True, max_length=100, verbose_name='Arena')),
                ('attendance', models.IntegerField(blank=True, null=True, verbose_name='Asistencia')),
                ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Metadatos de partido',
                'verbose_name_plural': 'Metadatos de partidos',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID del jugador')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nombre (opcional)')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team'),
        ),
        migrations.CreateModel(
            name='WinProbabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='Período')),
                ('time_remaining', models.CharField(blank=True, max_length=20, verbose_name='Tiempo restante')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Score local')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Score visitante')),
                ('win_pct', models.FloatField(blank=True, null=True, verbose_name='Win % (local)')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_probability_snapshots', to='core.game')),
            ],
            options={
                'verbose_name': 'Win probability snapshot',
                'verbose_name_plural': 'Win probability snapshots',
                'ordering': ['game', 'period'],
            },
        ),
        migrations.CreateModel(
            name='GameTeamLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_away', models.CharField(blank=True, max_length=10, verbose_name='Home/Away')),
                ('period', models.CharField(blank=True, default='ALL', max_length=10, verbose_name='Período (ALL/Q1/Q2/…)')),
                ('fgm', models.IntegerField(default=0, verbose_name='FGM')),
                ('fga', models.IntegerField(default=0, verbose_name='FGA')),
                ('fg_pct', models.FloatField(blank=True, null=True, verbose_name='FG%')),
                ('fg3m', models.IntegerField(default=0, verbose_name='3PM')),
                ('fg3a', models.IntegerField(default=0, verbose_name='3PA')),
                ('fg3_pct', models.FloatField(blank=True, null=True, verbose_name='3P%')),
                ('ftm', models.IntegerField(default=0, verbose_name='FTM')),
                ('fta', models.IntegerField(default=0, verbose_name='FTA')),
                ('ft_pct', models.FloatField(blank=True, null=True, verbose_name='FT%')),
                ('oreb', models.IntegerField(default=0, verbose_name='OREB')),
                ('dreb', models.IntegerField(default=0, verbose_name='DREB')),
                ('reb', models.IntegerField(default=0, verbose_name='REB')),
                ('ast', models.IntegerField(default=0, verbose_name='AST')),
                ('stl', models.IntegerField(default=0, verbose_name='STL')),
                ('blk', models.IntegerField(default=0, verbose_name='BLK')),
                ('tov', models.IntegerField(default=0, verbose_name='TOV')),
                ('pf', models.IntegerField(default=0, verbose_name='PF')),
                ('pts', models.IntegerField(default=0, verbose_name='PTS')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lines', to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_lines', to='core.team')),
            ],
            options={
                'verbose_name': 'Estadísticas equipo-partido',
                'verbose_name_plural': 'Estadísticas equipos-partidos',
                'ordering': ['game', 'team'],
                'indexes': [models.Index(fields=['game'], name='core_gamete_game_id_c7b013_idx'), models.Index(fields=['team'], name='core_gamete_team_id_ed5df0_idx')],
                'unique_together': {('game', 'team', 'period')},
            },
        ),
        migrations.CreateModel(
            name='GamePlayerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_away', models.CharField(blank=True, max_length=10, verbose_name='Home/Away')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Posición')),
                ('period', models.CharField(blank=True, default='ALL', max_length=10, verbose_name='Período (ALL/Q1/Q2/…)')),
                ('min_played', models.FloatField(blank=True, null=True, verbose_name='Minutos jugados')),
                ('fgm', models.IntegerField(default=0, verbose_name='Tiros de campo anotados')),
                ('fga', models.IntegerField(default=0, verbose_name='Tiros de campo intentados')),
                ('fg_pct', models.FloatField(blank=True, null=True, verbose_name='% Tiros de campo')),
                ('fg3m', models.IntegerField(default=0, verbose_name='Triples anotados')),
                ('fg3a', models.IntegerField(default=0, verbose_name='Triples intentados')),
                ('fg3_pct', models.FloatField(blank=True, null=True, verbose_name='% Triples')),
                ('ftm', models.IntegerField(default=0, verbose_name='Tiros libres anotados')),
                ('fta', models.IntegerField(default=0, verbose_name='Tiros libres intentados')),
                ('ft_pct', models.FloatField(blank=True, null=True, verbose_name='% Tiros libres')),
                ('oreb', models.IntegerField(default=0, verbose_name='Rebotes ofensivos')),
                ('dreb', models.IntegerField(default=0, verbose_name='Rebotes defensivos')),
                ('reb', models.IntegerField(default=0, verbose_name='Rebotes totales')),
                ('ast', models.IntegerField(default=0, verbose_name='Asistencias')),
                ('stl', models.IntegerField(default=0, verbose_name='Robos')),
                ('blk', models.IntegerField(default=0, verbose_name='Tapones')),
                ('tov', models.IntegerField(default=0, verbose_name='Pérdidas')),
                ('pf', models.IntegerField(default=0, verbose_name='Faltas personales')),
                ('pts', models.IntegerField(default=0, verbose_name='Puntos')),
                ('plus_minus', models.IntegerField(blank=True, null=True, verbose_name='±')),
                ('off_rating', models.FloatField(blank=True, null=True, verbose_name='Rating ofensivo')),
                ('def_rating', models.FloatField(blank=True, null=True, verbose_name='Rating defensivo')),
                ('net_rating', models.FloatField(blank=True, null=True, verbose_name='Net rating')),
                ('ast_pct', models.FloatField(blank=True, null=True, verbose_name='% Asistencias')),
                ('ast_to', models.FloatField(blank=True, null=True, verbose_name='AST/TO ratio')),
                ('ast_ratio', models.FloatField(blank=True, null=True, verbose_name='AST ratio')),
                ('oreb_pct', models.FloatField(blank=True, null=True, verbose_name='% Rebotes ofensivos')),
                ('dreb_pct', models.FloatField(blank=True, null=True, verbose_name='% Rebotes defensivos')),
                ('reb_pct', models.FloatField(blank=True, null=True, verbose_name='% Rebotes totales')),
                ('to_ratio', models.FloatField(blank=True, null=True, verbose_name='TO ratio')),
                ('efg_pct', models.FloatField(blank=True, null=True, verbose_name='eFG%')),
                ('ts_pct', models.FloatField(blank=True, null=True, verbose_name='TS%')),
                ('usg_pct', models.FloatField(blank=True, null=True, verbose_name='USG%')),
                ('pace', models.FloatField(blank=True, null=True, verbose_name='Pace')),
                ('pie', models.FloatField(blank=True, null=True, verbose_name='PIE')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_lines', to='core.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_lines', to='core.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_player_lines', to='core.team')),
            ],
            options={
                'verbose_name': 'Estadísticas jugador-partido',
                'verbose_name_plural': 'Estadísticas jugadores-partidos',
                'ordering': ['game', '-pts'],
                'indexes': [models.Index(fields=['game'], name='core_gamepl_game_id_6105ea_idx'), models.Index(fields=['player', 'game'], name='core_gamepl_player__93090d_idx'), models.Index(fields=['team', 'game'], name='core_gamepl_team_id_cb660c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'date'], name='core_game_season_078ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'season_type'], name='core_game_season_a2d524_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['league', 'season', 'date'], name='core_game_league_0d3a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='winprobabilitysnapshot',
            index=models.Index(fields=['game'], name='core_winpro_game_id_c0ad37_idx'),
        ),
    ]
