# Generated by Django 5.2 on 2026-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_boxscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gameboxscoreadvanced',
            new_name='game_boxsco_game_id_b8037d_idx',
            old_name='game_boxsco_game_id_8b9c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='gameboxscoreadvanced',
            new_name='game_boxsco_player__647f88_idx',
            old_name='game_boxsco_player__b2d4f6_idx',
        ),
        migrations.RenameIndex(
            model_name='gameboxscoreadvanced',
            new_name='game_boxsco_season_624ef8_idx',
            old_name='game_boxsco_season_0e1a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='gameboxscoretraditional',
            new_name='game_boxsco_game_id_077f3b_idx',
            old_name='game_boxsco_game_id_7a8b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='gameboxscoretraditional',
            new_name='game_boxsco_player__b2200d_idx',
            old_name='game_boxsco_player__a1c3e5_idx',
        ),
        migrations.RenameIndex(
            model_name='gameboxscoretraditional',
            new_name='game_boxsco_season_73f4be_idx',
            old_name='game_boxsco_season_9d4f6b_idx',
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='ast_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Assist %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='ast_ratio',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Assist Ratio'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='ast_to',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Assist/Turnover Ratio'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='away_team_abb',
            field=models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BKN', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards')], max_length=10, verbose_name='Equipo Visitante'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='def_rtg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Defensive Rating'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='dreb_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Defensive Rebound %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='efg_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Effective FG %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='home_team_abb',
            field=models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BKN', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards')], max_length=10, verbose_name='Equipo Local'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='net_rtg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Net Rating'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='off_rtg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Offensive Rating'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='oreb_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Offensive Rebound %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='pace',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pace'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='period',
            field=models.CharField(choices=[('All', 'Todo el juego'), ('Q1', '1er Cuarto'), ('Q2', '2do Cuarto'), ('Q3', '3er Cuarto'), ('Q4', '4to Cuarto'), ('OT1', 'Tiempo Extra 1'), ('OT2', 'Tiempo Extra 2'), ('OT3', 'Tiempo Extra 3'), ('OT4', 'Tiempo Extra 4'), ('1stHalf', '1ra Mitad'), ('2ndHalf', '2da Mitad'), ('AllOT', 'Todos los Tiempos Extra')], max_length=10, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='pie',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Player Impact Estimate'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='player_team_abb',
            field=models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BKN', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards')], max_length=10, verbose_name='Equipo del Jugador'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='reb_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rebound %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='season',
            field=models.CharField(choices=[('2015-16', '2015-16'), ('2016-17', '2016-17'), ('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26')], db_index=True, max_length=10, verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='season_type',
            field=models.CharField(choices=[('pre-season', 'Pre-Temporada'), ('regular-season', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('all-star', 'All-Star'), ('playin', 'Play-In'), ('ist', 'IST')], db_index=True, max_length=20, verbose_name='Tipo de Temporada'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='to_ratio',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Turnover Ratio'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='ts_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='True Shooting %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoreadvanced',
            name='usg_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Usage %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='ast',
            field=models.IntegerField(default=0, verbose_name='Assists'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='away_team_abb',
            field=models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BKN', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards')], max_length=10, verbose_name='Equipo Visitante'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='blk',
            field=models.IntegerField(default=0, verbose_name='Blocks'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='dreb',
            field=models.IntegerField(default=0, verbose_name='Defensive Rebounds'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='fg3_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='3 Point %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='fg3a',
            field=models.IntegerField(default=0, verbose_name='3 Pointers Attempted'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='fg3m',
            field=models.IntegerField(default=0, verbose_name='3 Pointers Made'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='fg_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Field Goal %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='fga',
            field=models.IntegerField(default=0, verbose_name='Field Goals Attempted'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='fgm',
            field=models.IntegerField(default=0, verbose_name='Field Goals Made'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='ft_pct',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Free Throw %'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='fta',
            field=models.IntegerField(default=0, verbose_name='Free Throws Attempted'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='ftm',
            field=models.IntegerField(default=0, verbose_name='Free Throws Made'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='game_id',
            field=models.CharField(db_index=True, help_text='Identificador único del juego', max_length=20, verbose_name='ID del Juego'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='home_team_abb',
            field=models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BKN', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards')], max_length=10, verbose_name='Equipo Local'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='min',
            field=models.CharField(help_text='Formato MM:SS', max_length=10, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='oreb',
            field=models.IntegerField(default=0, verbose_name='Offensive Rebounds'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='period',
            field=models.CharField(choices=[('All', 'Todo el juego'), ('Q1', '1er Cuarto'), ('Q2', '2do Cuarto'), ('Q3', '3er Cuarto'), ('Q4', '4to Cuarto'), ('OT1', 'Tiempo Extra 1'), ('OT2', 'Tiempo Extra 2'), ('OT3', 'Tiempo Extra 3'), ('OT4', 'Tiempo Extra 4'), ('1stHalf', '1ra Mitad'), ('2ndHalf', '2da Mitad'), ('AllOT', 'Todos los Tiempos Extra')], max_length=10, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='pf',
            field=models.IntegerField(default=0, verbose_name='Personal Fouls'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='player_pos',
            field=models.CharField(help_text='G, F, C, etc.', max_length=5, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='player_team_abb',
            field=models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BKN', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards')], max_length=10, verbose_name='Equipo del Jugador'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='plus_minus',
            field=models.IntegerField(default=0, verbose_name='Plus/Minus'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='pts',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='reb',
            field=models.IntegerField(default=0, verbose_name='Rebounds'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='season',
            field=models.CharField(choices=[('2015-16', '2015-16'), ('2016-17', '2016-17'), ('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26')], db_index=True, max_length=10, verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='season_type',
            field=models.CharField(choices=[('pre-season', 'Pre-Temporada'), ('regular-season', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('all-star', 'All-Star'), ('playin', 'Play-In'), ('ist', 'IST')], db_index=True, max_length=20, verbose_name='Tipo de Temporada'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='stl',
            field=models.IntegerField(default=0, verbose_name='Steals'),
        ),
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='to',
            field=models.IntegerField(default=0, verbose_name='Turnovers'),
        ),
    ]
