# Generated by Django 5.2 on 2025-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboxscoretraditional',
            name='season_type',
            field=models.CharField(choices=[('pre-season', 'Pre-Temporada'), ('regular-season', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('all-star', 'All-Star'), ('playin', 'Play-In'), ('ist', 'IST')], help_text='Tipo de temporada (pre-season, regular-season, playoffs)', max_length=20, verbose_name='Tipo de Temporada'),
        ),
        migrations.AlterField(
            model_name='gameplaybyplay',
            name='season_type',
            field=models.CharField(choices=[('pre-season', 'Pre-Temporada'), ('regular-season', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('all-star', 'All-Star'), ('playin', 'Play-In'), ('ist', 'IST')], help_text='Tipo de temporada (pre-season, regular-season, playoffs)', max_length=20, verbose_name='Tipo de Temporada'),
        ),
        migrations.AlterField(
            model_name='gamesummary',
            name='season_type',
            field=models.CharField(choices=[('pre-season', 'Pre-Temporada'), ('regular-season', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('all-star', 'All-Star'), ('playin', 'Play-In'), ('ist', 'IST')], help_text='Tipo de temporada (pre-season, regular-season, playoffs)', max_length=20, verbose_name='Tipo de Temporada'),
        ),
        migrations.AlterField(
            model_name='teamboxscoretraditional',
            name='season_type',
            field=models.CharField(choices=[('pre-season', 'Pre-Temporada'), ('regular-season', 'Temporada Regular'), ('playoffs', 'Playoffs'), ('all-star', 'All-Star'), ('playin', 'Play-In'), ('ist', 'IST')], help_text='Tipo de temporada (pre-season, regular-season, playoffs)', max_length=20, verbose_name='Tipo de Temporada'),
        ),
    ]
