"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vz+du974h9+nba#ix&ggwst-sqs8cgsd%@1txg^sht#d_^fmlt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["backend", "localhost", "127.0.0.1", "prometheus"]


# Application definition

INSTALLED_APPS = [
    # Prometheus debe ir primero
    "django_prometheus",
    # Unfold django theme
    "unfold",
    "crispy_forms",
    # Django apps - usar AdminConfig personalizado
    "project.admin.NBAAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    # Project apps
    "dashboard",
    "game",
    "game_boxscore",
    "ia",
    "lineups",
    "players",
    "predictions",
    "roster",
    "teams",
    # Project commands
    "project_commands",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "postgres",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# Static files configuration for development
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Evolveme
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "")

ADMIN_GROUPS = os.getenv("ADMIN_GROUPS", "").split(",")
ROLE_PERMISSIONS = {
    "owner": [],
}

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]
CRISPY_TEMPLATE_PACK = "unfold_crispy"

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Cache configuration con Redis
CACHES = {
    "default": {
        "BACKEND": "django_prometheus.cache.backends.redis.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Session configuration
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Celery Configuration
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Static files
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "NBA Data Manager",
    "SITE_HEADER": "NBA Data Manager",
    "SITE_SUBHEADER": "Panel de Administración",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/ico.png",
        "dark": lambda request: "/static/ico.png",
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: "/static/ico.png",
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "BORDER_RADIUS": "8px",
    "THEME": None,  # Permite cambio de tema (claro/oscuro)
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            # Colores azules más vibrantes
            "50": "oklch(98% .02 240)",  # Azul muy claro
            "100": "oklch(95% .04 240)",  # Azul claro
            "200": "oklch(90% .08 240)",  # Azul medio-claro
            "300": "oklch(82% .15 240)",  # Azul medio
            "400": "oklch(70% .25 240)",  # Azul
            "500": "oklch(60% .3 240)",  # Azul principal
            "600": "oklch(50% .3 240)",  # Azul oscuro
            "700": "oklch(42% .25 240)",  # Azul más oscuro
            "800": "oklch(35% .2 240)",  # Azul muy oscuro
            "900": "oklch(28% .15 240)",  # Azul casi negro
            "950": "oklch(20% .1 240)",  # Azul negro
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
}

NBA_TEAMS_INFO = {
    "Atlanta Hawks": ["ATL", 1610612737, "East", "Southeast"],
    "Boston Celtics": ["BOS", 1610612738, "East", "Atlantic"],
    "Brooklyn Nets": ["BKN", 1610612751, "East", "Atlantic"],
    "Charlotte Hornets": ["CHA", 1610612766, "East", "Southeast"],
    "Chicago Bulls": ["CHI", 1610612741, "East", "Central"],
    "Cleveland Cavaliers": ["CLE", 1610612739, "East", "Central"],
    "Dallas Mavericks": ["DAL", 1610612742, "West", "Southwest"],
    "Denver Nuggets": ["DEN", 1610612743, "West", "Northwest"],
    "Detroit Pistons": ["DET", 1610612765, "East", "Central"],
    "Golden State Warriors": ["GSW", 1610612744, "West", "Pacific"],
    "Houston Rockets": ["HOU", 1610612745, "West", "Southwest"],
    "Indiana Pacers": ["IND", 1610612754, "East", "Central"],
    "Los Angeles Clippers": ["LAC", 1610612746, "West", "Pacific"],
    "Los Angeles Lakers": ["LAL", 1610612747, "West", "Pacific"],
    "Memphis Grizzlies": ["MEM", 1610612763, "West", "Southwest"],
    "Miami Heat": ["MIA", 1610612748, "East", "Southeast"],
    "Milwaukee Bucks": ["MIL", 1610612749, "East", "Central"],
    "Minnesota Timberwolves": ["MIN", 1610612750, "West", "Northwest"],
    "New Orleans Pelicans": ["NOP", 1610612740, "West", "Southwest"],
    "New York Knicks": ["NYK", 1610612752, "East", "Atlantic"],
    "Oklahoma City Thunder": ["OKC", 1610612760, "West", "Northwest"],
    "Orlando Magic": ["ORL", 1610612753, "East", "Southeast"],
    "Philadelphia 76ers": ["PHI", 1610612755, "East", "Atlantic"],
    "Phoenix Suns": ["PHX", 1610612756, "West", "Pacific"],
    "Portland Trail Blazers": ["POR", 1610612757, "West", "Northwest"],
    "Sacramento Kings": ["SAC", 1610612758, "West", "Pacific"],
    "San Antonio Spurs": ["SAS", 1610612759, "West", "Southwest"],
    "Toronto Raptors": ["TOR", 1610612761, "East", "Atlantic"],
    "Utah Jazz": ["UTA", 1610612762, "West", "Northwest"],
    "Washington Wizards": ["WAS", 1610612764, "East", "Southeast"],
}

# Glossary of NBA terms

LINEUPS_GLOSSARY = {
    # Estadísticas Básicas Tradicionales
    "GP": "Partidos Jugados",
    "MIN": "Minutos Jugados",
    "PTS": "Puntos",
    "FGM": "Tiros de Campo Anotados",
    "FGA": "Tiros de Campo Intentados",
    "FG%": "Porcentaje de Tiros de Campo",
    "FG_PCT": "Porcentaje de Tiros de Campo",
    "THREE_P_M": "Tiros de Campo de Tres Puntos Anotados",
    "FG3M": "Tiros de Campo de Tres Puntos Anotados",
    "THREE_P_A": "Tiros de Campo de Tres Puntos Intentados",
    "FG3A": "Tiros de Campo de Tres Puntos Intentados",
    "THREE_P_PCT": "Porcentaje de Tiros de Campo de Tres Puntos",
    "FG3_PCT": "Porcentaje de Tiros de Campo de Tres Puntos",
    "FTM": "Tiros Libres Anotados",
    "FTA": "Tiros Libres Intentados",
    "FT%": "Porcentaje de Tiros Libres",
    "FT_PCT": "Porcentaje de Tiros Libres",
    "OREB": "Rebotes Ofensivos",
    "DREB": "Rebotes Defensivos",
    "REB": "Rebotes",
    "AST": "Asistencias",
    "TOV": "Pérdidas de Balón",
    "STL": "Robos",
    "BLK": "Tapones",
    "BLKA": "Tapones Recibidos",
    "PF": "Faltas Personales",
    "PFD": "Faltas Personales Provocadas",
    "+/-": "Más/Menos",
    "PLUS_MINUS": "Más/Menos",
    # Estadísticas Avanzadas
    "OFFRTG": "Clasificación Ofensiva",
    "OFF_RATING": "Clasificación Ofensiva",
    "DEFRTG": "Clasificación Defensiva",
    "DEF_RATING": "Clasificación Defensiva",
    "NETRTG": "Clasificación Neta",
    "NET_RATING": "Clasificación Neta",
    "AST%": "Porcentaje de Asistencias",
    "AST_PCT": "Porcentaje de Asistencias",
    "AST/TO": "Ratio de Asistencias por Pérdida de Balón",
    "AST_TO": "Ratio de Asistencias por Pérdida de Balón",
    "AST RATIO": "Ratio de Asistencias",
    "AST_RATIO": "Ratio de Asistencias",
    "OREB%": "Porcentaje de Rebotes Ofensivos",
    "OREB_PCT": "Porcentaje de Rebotes Ofensivos",
    "DREB%": "Porcentaje de Rebotes Defensivos",
    "DREB_PCT": "Porcentaje de Rebotes Defensivos",
    "REB%": "Porcentaje de Rebotes",
    "REB_PCT": "Porcentaje de Rebotes",
    "TO RATIO": "Ratio de Pérdidas de Balón",
    "TM_TOV_PCT": "Ratio de Pérdidas de Balón",
    "TO_RATIO": "Ratio de Pérdidas de Balón",
    "EFG%": "Porcentaje Efectivo de Tiros de Campo",
    "EFG_PCT": "Porcentaje Efectivo de Tiros de Campo",
    "TS%": "Porcentaje Real de Tiros",
    "TS_PCT": "Porcentaje Real de Tiros",
    "PACE": "Ritmo de Juego",
    "PIE": "Estimación de Impacto del Jugador",
    # Estadísticas Misceláneas
    "OFF_TO": "Puntos Tras Pérdidas de Balón",
    "PTS_OFF_TOV": "Puntos Tras Pérdidas de Balón",
    "TWO_P_ND_PTS": "Puntos de Segunda Oportunidad",
    "PTS_2ND_CHANCE": "Puntos de Segunda Oportunidad",
    "FBPS": "Puntos al Contraataque",
    "PTS_FB": "Puntos al Contraataque",
    "PITP": "Puntos en la Zona Pintada",
    "PTS_PAINT": "Puntos en la Zona Pintada",
    # Estadísticas del Oponente
    "OPP_OFF_TO": "Puntos del Oponente Tras Pérdidas de Balón",
    "OPP_PTS_OFF_TOV": "Puntos del Oponente Tras Pérdidas de Balón",
    "OPP_2ND_PTS": "Puntos de Segunda Oportunidad del Oponente",
    "OPP_PTS_2ND_CHANCE": "Puntos de Segunda Oportunidad del Oponente",
    "OPP_FBPS": "Puntos al Contraataque del Oponente",
    "OPP_PTS_FB": "Puntos al Contraataque del Oponente",
    "OPP_PITP": "Puntos en la Zona Pintada del Oponente",
    "OPP_PTS_PAINT": "Puntos en la Zona Pintada del Oponente",
    "OPP_FGM": "Tiros de Campo Anotados por el Oponente",
    "OPP_FGA": "Tiros de Campo Intentados por el Oponente",
    "OPP_FG%": "Porcentaje de Tiros de Campo del Oponente",
    "OPP_FG_PCT": "Porcentaje de Tiros de Campo del Oponente",
    "OPP_3PM": "Tiros de Campo de 3 Puntos Anotados por el Oponente",
    "OPP_FG3M": "Tiros de Campo de 3 Puntos Anotados por el Oponente",
    "OPP_3PA": "Tiros de Campo de 3 Puntos Intentados por el Oponente",
    "OPP_FG3A": "Tiros de Campo de 3 Puntos Intentados por el Oponente",
    "OPP_3P%": "Porcentaje de Tiros de Campo de 3 Puntos del Oponente",
    "OPP_FG3_PCT": "Porcentaje de Tiros de Campo de 3 Puntos del Oponente",
    "OPP_FTM": "Tiros Libres Anotados por el Oponente",
    "OPP_FTA": "Tiros Libres Intentados por el Oponente",
    "OPP_FT%": "Porcentaje de Tiros Libres del Oponente",
    "OPP_FT_PCT": "Porcentaje de Tiros Libres del Oponente",
    "OPP_OREB": "Rebotes Ofensivos del Oponente",
    "OPP_DREB": "Rebotes Defensivos del Oponente",
    "OPP_REB": "Rebotes del Oponente",
    "OPP_AST": "Asistencias del Oponente",
    "OPP_TOV": "Pérdidas de Balón del Oponente",
    "OPP_STL": "Robos del Oponente",
    "OPP_BLK": "Tapones del Oponente",
    "OPP_BLKA": "Tiros de Campo Bloqueados Intentados por el Oponente",
    "OPP_PF": "Faltas Personales del Oponente",
    "OPP_PFD": "Faltas Personales Recibidas por el Oponente",
    "OPP_PTS": "Puntos del Oponente",
    # Four Factors
    "EFG%": "Porcentaje Efectivo de Tiros de Campo",
    "FTA RATE": "Tasa de Intentos de Tiros Libres",
    "FTA_RATE": "Tasa de Intentos de Tiros Libres",
    "TO RATIO%": "Porcentaje de Ratio de Pérdidas de Balón",
    "OPP FTA RATE": "Tasa de Intentos de Tiros Libres del Oponente",
    "OPP_FTA_RATE": "Tasa de Intentos de Tiros Libres del Oponente",
    "OPP EFG%": "Porcentaje Efectivo de Tiros de Campo del Oponente",
    "OPP_EFG_PCT": "Porcentaje Efectivo de Tiros de Campo del Oponente",
    "OPP OREB%": "Porcentaje de Rebotes Ofensivos del Oponente",
    "OPP_OREB_PCT": "Porcentaje de Rebotes Ofensivos del Oponente",
    "OPP TO RATIO%": "Porcentaje de Ratio de Pérdidas de Balón del Oponente",
    "OPP_TOV_PCT": "Porcentaje de Ratio de Pérdidas de Balón del Oponente",
    # Estadísticas de Anotación
    "PCT_FGA": "Porcentaje de Intentos de Tiros de Campo",
    "PCT_FGA_2PT": "Porcentaje de Intentos de Tiros de Campo (2 Puntos)",
    "PCT_FGA_3PT": "Porcentaje de Intentos de Tiros de Campo (3 Puntos)",
    "PCT_PTS": "Porcentaje de Puntos",
    "PCT_PTS_2PT": "Porcentaje de Puntos (2 Puntos)",
    "PCT_PTS_2PT_MR": "Porcentaje de Puntos (Media Distancia)",
    "PCT_PTS_3PT": "Porcentaje de Puntos (3 Puntos)",
    "PCT_PTS_FB": "Porcentaje de Puntos (Puntos de Contraataque)",
    "PCT_PTS_FT": "Porcentaje de Puntos (Tiros Libres)",
    "PCT_PTS_OFF_TOV": "Porcentaje de Puntos (Tras Pérdidas de Balón)",
    "PCT_PTS_PAINT": "Porcentaje de Puntos (Puntos en la Pintura)",
    "TWO_P_FGM": "Tiros de Campo de 2 Puntos Anotados",
    "FG2M": "Tiros de Campo de 2 Puntos Anotados",
    "PCT_AST": "Porcentaje de Asistencias",
    "PCT_AST_2PM": "Porcentaje de Tiros de Campo de 2 Puntos Anotados Asistidos",
    "PCT_UAST_2PM": "Porcentaje de Tiros de Campo de 2 Puntos Anotados Sin Asistencia",
    "THREE_P_FGM": "Tiros de Campo de 3 Puntos Anotados",
    "FG3M": "Tiros de Campo de 3 Puntos Anotados",
    "PCT_AST_3PM": "Porcentaje de Tiros de Campo de 3 Puntos Anotados Asistidos",
    "PCT_UAST_3PM": "Porcentaje de Tiros de Campo de 3 Puntos Anotados Sin Asistencia",
    "FGM": "Tiros de Campo Anotados",
    "PCT_AST_FGM": "Porcentaje de Tiros de Campo Anotados Asistidos",
    "PCT_UAST_FGM": "Porcentaje de Tiros de Campo Anotados Sin Asistencia",
}
PLAYERS_GLOSSARY = {
    # Basic Statistics
    "GP": "Games Played",
    "W": "Wins",
    "L": "Losses",
    "MIN": "Minutes Played",
    "PTS": "Points",
    "POINTS": "Points",
    # Player Information
    "AGE": "Age",
    "HEIGHT": "Height",
    "WEIGHT": "Weight",
    "COLLEGE": "College",
    "COUNTRY": "Country",
    "DRAFT_YEAR": "Draft Year",
    "DRAFT_ROUND": "Draft Round",
    "DRAFT_NUMBER": "Draft Number",
    # Field Goals
    "FGM": "Field Goals Made",
    "FGA": "Field Goals Attempted",
    "FG_PCT": "Field Goal Percentage",
    "EFG_PCT": "Effective Field Goal Percentage",
    "FG2M": "2 Point Field Goals Made",
    "TWO_P_FGM": "2 Point Field Goals Made",
    "FG2A": "2 Point Field Goals Attempted",
    "TWO_P_FGA": "2 Point Field Goals Attempted",
    "FG2_PCT": "2 Point Field Goal Percentage",
    "FG2_PCT_ALT": "2 Point Field Goal Percentage",
    "TWO_P_FG_PCT": "2 Point Field Goal Percentage",
    "TWO_P_FG_PCT_ALT": "2 Point Field Goal Percentage",
    # 3-Point Field Goals
    "FG3M": "3 Point Field Goals Made",
    "FG3A": "3 Point Field Goals Attempted",
    "FG3_PCT": "3 Point Field Goal Percentage",
    "THREE_P_FGM": "3 Point Field Goals Made",
    "THREE_P_FGA": "3 Point Field Goals Attempted",
    "THREE_P_FG_PCT": "3 Point Field Goal Percentage",
    "THREE_P_FG_PCT_ALT": "3 Point Field Goal Percentage",
    # Free Throws
    "FTM": "Free Throws Made",
    "FTA": "Free Throws Attempted",
    "FT_PCT": "Free Throw Percentage",
    # Rebounds
    "OREB": "Offensive Rebounds",
    "DREB": "Defensive Rebounds",
    "REB": "Rebounds",
    "OREB_PCT": "Offensive Rebounding Percentage",
    "DREB_PCT": "Defensive Rebounding Percentage",
    "REB_PCT": "Rebounding Percentage",
    # Assists and Turnovers
    "AST": "Assists",
    "AST_PCT": "Assist Percentage",
    "AST_TO": "Assist to Turnover Ratio",
    "AST_RATIO": "Assist Ratio",
    "TOV": "Turnovers",
    "TO": "Turnovers",
    "TM_TOV_PCT": "Turnover Ratio",
    "TO_RATIO": "Turnover Ratio",
    # Steals and Blocks
    "STL": "Steals",
    "BLK": "Blocks",
    "BLKA": "Blocks Against",
    # Fouls
    "PF": "Personal Fouls",
    "PFD": "Personal Fouls Drawn",
    # Advanced Statistics
    "OFF_RATING": "Offensive Rating",
    "OFFRTG": "Offensive Rating",
    "DEF_RATING": "Defensive Rating",
    "DEFRTG": "Defensive Rating",
    "NET_RATING": "Net Rating",
    "NETRTG": "Net Rating",
    "TS_PCT": "True Shooting Percentage",
    "PACE": "Pace",
    "PIE": "Player Impact Estimate",
    "POSS": "Possessions",
    "USG_PCT": "Usage Percentage",
    # Plus-Minus
    "PLUS_MINUS": "Plus-Minus",
    "PLUSMINUS": "Plus-Minus",
    # Scoring Categories
    "PTS_OFF_TOV": "Points Off Turnovers",
    "PTS_OFF_TO": "Points Off Turnovers",
    "PTS_2ND_CHANCE": "Second Chance Points",
    "SECOND_CHANCE_PTS": "Second Chance Points",
    "PTS_FB": "Fast Break Points",
    "FBPS": "Fast Break Points",
    "PTS_PAINT": "Points in the Paint",
    "PITP": "Points in the Paint",
    # Shooting Percentages by Distance
    "PCT_FGA_2PT": "Percent of Field Goals Attempted (2 Pointers)",
    "PCT_FGA_3PT": "Percent of Field Goals Attempted (3 Pointers)",
    "PCT_PTS_2PT": "Percent of Points (2 Pointers)",
    "PCT_PTS_2PT_MR": "Percent of Points (Mid-Range)",
    "PCT_PTS_3PT": "Percent of Points (3 Pointers)",
    "PCT_PTS_FB": "Percent of Points (Fast Break Points)",
    "PCT_PTS_FT": "Percent of Points (Free Throws)",
    "PCT_PTS_OFF_TOV": "Percent of Points (Off Turnovers)",
    "PCT_PTS_PAINT": "Percent of Points (Points in the Paint)",
    # Assisted vs Unassisted
    "PCT_AST_2PM": "Percent of 2 Point Field Goals Made Assisted",
    "TWO_P_FGM_PCT_AST": "Percent of 2 Point Field Goals Made Assisted",
    "PCT_UAST_2PM": "Percent of 2 Point Field Goals Made Unassisted",
    "TWO_P_FGM_PCT_UAST": "Percent of 2 Point Field Goals Made Unassisted",
    "PCT_AST_3PM": "Percent of 3 Point Field Goals Made Assisted",
    "THREE_P_FGM_PCT_AST": "Percent of 3 Point Field Goals Made Assisted",
    "PCT_UAST_3PM": "Percent of 3 Point Field Goals Made Unassisted",
    "THREE_P_FGM_PCT_UAST": "Percent of 3 Point Field Goals Made Unassisted",
    "PCT_AST_FGM": "Percent of Field Goals Made Assisted",
    "FGM_PCT_AST": "Percent of Field Goals Made Assisted",
    "PCT_UAST_FGM": "Percent of Field Goals Made Unassisted",
    "FGM_PCT_UAST": "Percent of Field Goals Made Unassisted",
    # Team Percentage Statistics
    "PCT_FGM": "Percent of Team's Field Goals Made",
    "PCT_FGA": "Percent of Team's Field Goals Attempted",
    "PCT_THREE_P_FGM": "Percent of Team's 3PT Field Goals Made",
    "PCT_THREE_P_FGM_ALT": "Percent of Team's 3PT Field Goals Made",
    "PCT_THREE_P_FGA": "Percent of Team's 3PT Field Goals Attempted",
    "PCT_THREE_P_FGA_ALT": "Percent of Team's 3PT Field Goals Attempted",
    "PCT_FTM": "Percent of Team's Free Throws Made",
    "PCT_FTA": "Percent of Team's Free Throws Attempted",
    "PCT_OREB": "Percent of Team's Offensive Rebounds",
    "PCT_DREB": "Percent of Team's Defensive Rebounds",
    "PCT_REB": "Percent of Team's Total Rebounds",
    "PCT_AST": "Percent of Team's Assists",
    "PCT_TOV": "Percent of Team's Turnovers",
    "TOV_PCT": "Percent of Team's Turnovers",
    "PCT_STL": "Percent of Team's Steals",
    "PCT_BLK": "Percent of Team's Blocks",
    "PCT_BLKA": "Percent of Team's Blocked Field Goal Attempts",
    "PCT_PF": "Percent of Team's Personal Fouls",
    "PF_PCT": "Percent of Team's Personal Fouls",
    "PCT_PFD": "Percent of Team's Personal Fouls Drawn",
    "PCT_PTS": "Percent of Team's Points",
    "PTS_PCT": "Points Percentage",
    # Opponent Statistics
    "OPP_FGM": "Opponent's Field Goals Made",
    "OPP_FGA": "Opponent's Field Goals Attempted",
    "OPP_FG_PCT": "Opponent's Field Goal Percentage",
    "OPP_FG3M": "Opponent's 3 Point Field Goals Made",
    "OPP_3PM": "Opponent's 3 Point Field Goals Made",
    "OPP_FG3A": "Opponent's 3 Point Field Goals Attempted",
    "OPP_3PA": "Opponent's 3 Point Field Goals Attempted",
    "OPP_FG3_PCT": "Opponent's 3 Point Field Goal Percentage",
    "OPP_3P_PCT": "Opponent's 3 Point Field Goal Percentage",
    "OPP_FTM": "Opponent's Free Throws Made",
    "OPP_FTA": "Opponent's Free Throws Attempted",
    "OPP_FT_PCT": "Opponent's Free Throw Percentage",
    "OPP_OREB": "Opponent's Offensive Rebounds",
    "OPP_DREB": "Opponent's Defensive Rebounds",
    "OPP_REB": "Opponent's Rebounds",
    "OPP_AST": "Opponent's Assists",
    "OPP_TOV": "Opponent's Turnovers",
    "OPP_STL": "Opponent's Steals",
    "OPP_BLK": "Opponent's Blocks",
    "OPP_BLKA": "Opponent's Blocked Field Goal Attempts",
    "OPP_PF": "Opponent's Personal Fouls",
    "OPP_PFD": "Opponent's Personal Fouls Drawn",
    "OPP_PTS": "Opponent's Points",
    "OPP_PTS_OFF_TOV": "Opponent Points Off Turnovers",
    "OPP_PTS_OFF_TO": "Opponent Points Off Turnovers",
    "OPP_PTS_2ND_CHANCE": "Opponent 2nd Chance Points",
    "OPP_2ND_PTS": "Opponent 2nd Chance Points",
    "OPP_PTS_FB": "Opponent Fast Break Points",
    "OPP_FBPS": "Opponent Fast Break Points",
    "OPP_PTS_PAINT": "Opponent Points in the Paint",
    "OPP_PITP": "Opponent Points in the Paint",
    "OPP_EFG_PCT": "Opponent Effective Field Goal Percentage",
    "OPP_FTA_RATE": "Opponent Free Throw Attempt Rate",
    "OPP_TOV_PCT": "Opponent Turnover Percentage",
    "OPP_OREB_PCT": "Opponent Offensive Rebounding Percentage",
    # Defense Statistics
    "DEF_RIM_FGM": "Defensive Rim Field Goals Made",
    "DEF_RIM_FGA": "Defensive Rim Field Goals Attempted",
    "DEF_RIM_FG_PCT": "Defensive Rim Field Goal Percentage",
    # Estimated Statistics
    "E_OFF_RATING": "Estimated Offensive Rating",
    "E_OFFRTG": "Estimated Offensive Rating",
    "E_DEF_RATING": "Estimated Defensive Rating",
    "E_DEFRTG": "Estimated Defensive Rating",
    "E_NET_RATING": "Estimated Net Rating",
    "E_NETRTG": "Estimated Net Rating",
    "E_AST_RATIO": "Estimated Assist Ratio",
    "E_OREB_PCT": "Estimated Offensive Rebound Percentage",
    "E_DREB_PCT": "Estimated Defensive Rebound Percentage",
    "E_REB_PCT": "Estimated Rebound Percentage",
    "E_TM_TOV_PCT": "Estimated Turnover Ratio",
    "E_PACE": "Estimated Pace",
    # Playtype Statistics
    "POSS_PCT": "Possession Percentage",
    "PPP": "Points Per Possession",
    "FREQ": "Frequency",
    "FREQ_PCT": "Frequency",
    "FT_POSS_PCT": "Free Throw Possession Percentage",
    "FT_FREQ_PCT": "Free Throw Frequency",
    "TOV_POSS_PCT": "Turnover Possession Percentage",
    "TOV_FREQ_PCT": "Turnover Frequency",
    "SF_POSS_PCT": "Shooting Foul Possession Percentage",
    "SF": "Shooting Foul",
    "SF_FREQ_PCT": "Shooting Foul Frequency",
    "PLUSONE_POSS_PCT": "And One Possession Percentage",
    "AND_ONE": "And One",
    "AND_ONE_FREQ_PCT": "And One Frequency",
    "SCORE_POSS_PCT": "Score Possession Percentage",
    "SCORE": "Score",
    "SCORE_FREQ_PCT": "Score Frequency",
    "PERCENTILE": "Percentile",
    # Shooting by Distance
    "FGM_LT5": "Less Than 5 ft. Field Goals Made",
    "FGA_LT5": "Less Than 5 ft. Field Goals Attempted",
    "FG_PCT_LT5": "Less Than 5 ft. Field Goal Percentage",
    "FGM_5_9": "5-9 ft. Field Goals Made",
    "FGA_5_9": "5-9 ft. Field Goals Attempted",
    "FG_PCT_5_9": "5-9 ft. Field Goal Percentage",
    "FGM_10_14": "10-14 ft. Field Goals Made",
    "FGA_10_14": "10-14 ft. Field Goals Attempted",
    "FG_PCT_10_14": "10-14 ft. Field Goal Percentage",
    "FGM_15_19": "15-19 ft. Field Goals Made",
    "FGA_15_19": "15-19 ft. Field Goals Attempted",
    "FG_PCT_15_19": "15-19 ft. Field Goal Percentage",
    "FGM_20_24": "20-24 ft. Field Goals Made",
    "FGA_20_24": "20-24 ft. Field Goals Attempted",
    "FG_PCT_20_24": "20-24 ft. Field Goal Percentage",
    "FGM_25_29": "25-29 ft. Field Goals Made",
    "FGA_25_29": "25-29 ft. Field Goals Attempted",
    "FG_PCT_25_29": "25-29 ft. Field Goal Percentage",
    "FGM_LT_06": "Less Than 0.6 ft. Field Goals Made",
    "FGA_LT_06": "Less Than 0.6 ft. Field Goals Attempted",
    "LT_06_PCT": "Less Than 0.6 ft. Field Goal Percentage",
    "FGM_LT_10": "Less Than 10 ft. Field Goals Made",
    "FGA_LT_10": "Less Than 10 ft. Field Goals Attempted",
    "LT_10_PCT": "Less Than 10 ft. Field Goal Percentage",
    "FGM_GT_15": "Greater Than 15 ft. Field Goals Made",
    "FGA_GT_15": "Greater Than 15 ft. Field Goals Attempted",
    "GT_15_PCT": "Greater Than 15 ft. Field Goal Percentage",
    # Violations
    "TRAVEL": "Travel",
    "DOUBLE_DRIBBLE": "Double Dribble",
    "DISCONTINUED_DRIBBLE": "Discontinued Dribble",
    "OFF_THREE_SEC": "Offensive Three Seconds",
    "FIVE_SEC": "Five Seconds",
    "EIGHT_SEC": "Eight Seconds",
    "SHOT_CLOCK": "Shot Clock Violation",
    "INBOUND": "Inbound Violation",
    "BACKCOURT": "Backcourt Violation",
    "OFF_GOALTENDING": "Offensive Goaltending",
    "PALMING": "Palming",
    "OFF_FOUL": "Offensive Foul",
    "DEF_THREE_SEC": "Defensive Three Seconds",
    "CHARGE": "Charge",
    "DELAY_OF_GAME": "Delay of Game",
    "DEF_GOALTENDING": "Defensive Goaltending",
    "LANE": "Lane Violation",
    "JUMP_BALL": "Jump Ball",
    "KICKED_BALL": "Kicked Ball",
    # Tracking Statistics
    "DRIVES": "Drives",
    "DRIVE_FGM": "Drive Field Goals Made",
    "DRIVE_FGA": "Drive Field Goals Attempted",
    "DRIVE_FG_PCT": "Drive Field Goal Percentage",
    "DRIVE_FTM": "Drive Free Throws Made",
    "DRIVE_FTA": "Drive Free Throws Attempted",
    "DRIVE_FT_PCT": "Drive Free Throw Percentage",
    "DRIVE_PTS": "Drive Points",
    "DRIVE_PTS_PCT": "Drive Points Percentage",
    "DRIVE_PASSES": "Drive Passes",
    "DRIVE_PASSES_PCT": "Drive Passes Percentage",
    "DRIVE_AST": "Drive Assists",
    "DRIVE_AST_PCT": "Drive Assists Percentage",
    "DRIVE_TOV": "Drive Turnovers",
    "DRIVE_TOV_PCT": "Drive Turnovers Percentage",
    "DRIVE_PF": "Drive Personal Fouls",
    "DRIVE_PF_PCT": "Drive Personal Fouls Percentage",
    # Catch and Shoot
    "CATCH_SHOOT_PTS": "Catch and Shoot Points",
    "CATCH_SHOOT_FGM": "Catch and Shoot Field Goals Made",
    "CATCH_SHOOT_FGA": "Catch and Shoot Field Goals Attempted",
    "CATCH_SHOOT_FG_PCT": "Catch and Shoot Field Goal Percentage",
    "CATCH_SHOOT_FG3M": "Catch and Shoot 3 Point Field Goals Made",
    "CATCH_SHOOT_FG3A": "Catch and Shoot 3 Point Field Goals Attempted",
    "CATCH_SHOOT_FG3_PCT": "Catch and Shoot 3 Point Field Goal Percentage",
    "CATCH_SHOOT_EFG_PCT": "Catch and Shoot Effective Field Goal Percentage",
    # Pull Up
    "PULL_UP_PTS": "Pull Up Points",
    "PULL_UP_FGM": "Pull Up Field Goals Made",
    "PULL_UP_FGA": "Pull Up Field Goals Attempted",
    "PULL_UP_FG_PCT": "Pull Up Field Goal Percentage",
    "PULL_UP_FG3M": "Pull Up 3 Point Field Goals Made",
    "PULL_UP_FG3A": "Pull Up 3 Point Field Goals Attempted",
    "PULL_UP_FG3_PCT": "Pull Up 3 Point Field Goal Percentage",
    "PULL_UP_EFG_PCT": "Pull Up Effective Field Goal Percentage",
    # Touches
    "TOUCHES": "Touches",
    "FRONT_CT_TOUCHES": "Front Court Touches",
    "TIME_OF_POSS": "Time of Possession",
    "AVG_SEC_PER_TOUCH": "Average Seconds Per Touch",
    "AVG_DRIB_PER_TOUCH": "Average Dribbles Per Touch",
    "PTS_PER_TOUCH": "Points Per Touch",
    "ELBOW_TOUCHES": "Elbow Touches",
    "POST_TOUCHES": "Post Touches",
    "PAINT_TOUCHES": "Paint Touches",
    "PTS_PER_ELBOW_TOUCH": "Points Per Elbow Touch",
    "PTS_PER_POST_TOUCH": "Points Per Post Touch",
    "PTS_PER_PAINT_TOUCH": "Points Per Paint Touch",
    # Touch Statistics
    "ELBOW_TOUCH_FGM": "Elbow Touch Field Goals Made",
    "ELBOW_TOUCH_FGA": "Elbow Touch Field Goals Attempted",
    "ELBOW_TOUCH_FG_PCT": "Elbow Touch Field Goal Percentage",
    "ELBOW_TOUCH_FTM": "Elbow Touch Free Throws Made",
    "ELBOW_TOUCH_FTA": "Elbow Touch Free Throws Attempted",
    "ELBOW_TOUCH_FT_PCT": "Elbow Touch Free Throw Percentage",
    "ELBOW_TOUCH_PTS": "Elbow Touch Points",
    "ELBOW_TOUCH_PTS_PCT": "Elbow Touch Points Percentage",
    "ELBOW_TOUCH_PASSES": "Elbow Touch Passes",
    "ELBOW_TOUCH_PASSES_PCT": "Elbow Touch Passes Percentage",
    "ELBOW_TOUCH_PASS_PCT": "Elbow Touch Pass Percentage",
    "ELBOW_TOUCH_AST": "Elbow Touch Assists",
    "ELBOW_TOUCH_AST_PCT": "Elbow Touch Percent of Team's Assists",
    "ELBOW_TOUCH_TOV": "Elbow Touch Turnovers",
    "ELBOW_TOUCH_TOV_PCT": "Elbow Touch Percent of Team's Turnovers",
    "ELBOW_TOUCH_FOULS": "Elbow Touch Fouls",
    "ELBOW_TOUCH_FOULS_PCT": "Elbow Touch Fouls Percentage",
    "ELBOW_TOUCH_PF": "Elbow Touch Personal Fouls",
    "ELBOW_TOUCH_PF_PCT": "Elbow Touch Percent of Team's Personal Fouls",
    "POST_TOUCH_FGM": "Post Touch Field Goals Made",
    "POST_TOUCH_FGA": "Post Touch Field Goals Attempted",
    "POST_TOUCH_FG_PCT": "Post Touch Field Goal Percentage",
    "POST_TOUCH_FTM": "Post Touch Free Throws Made",
    "POST_TOUCH_FTA": "Post Touch Free Throws Attempted",
    "POST_TOUCH_FT_PCT": "Post Touch Free Throw Percentage",
    "POST_TOUCH_PTS": "Post Touch Points",
    "POST_TOUCH_PTS_PCT": "Post Touch Points Percentage",
    "POST_TOUCH_PASSES": "Post Touch Passes",
    "POST_TOUCH_PASSES_PCT": "Post Touch Passes Percentage",
    "POST_TOUCH_PASS_PCT": "Post Touch Pass Percentage",
    "POST_TOUCH_AST": "Post Touch Assists",
    "POST_TOUCH_AST_PCT": "Post Touch Percent of Team's Assists",
    "POST_TOUCH_TOV": "Post Touch Turnovers",
    "POST_TOUCH_TOV_PCT": "Post Touch Percent of Team's Turnovers",
    "POST_TOUCH_FOULS": "Post Touch Fouls",
    "POST_TOUCH_FOULS_PCT": "Post Touch Fouls Percentage",
    "POST_TOUCH_PF": "Post Touch Personal Fouls",
    "POST_TOUCH_PF_PCT": "Post Touch Percent of Team's Personal Fouls",
    "PAINT_TOUCH_FGM": "Paint Touch Field Goals Made",
    "PAINT_TOUCH_FGA": "Paint Touch Field Goals Attempted",
    "PAINT_TOUCH_FG_PCT": "Paint Touch Field Goal Percentage",
    "PAINT_TOUCH_FTM": "Paint Touch Free Throws Made",
    "PAINT_TOUCH_FTA": "Paint Touch Free Throws Attempted",
    "PAINT_TOUCH_FT_PCT": "Paint Touch Free Throw Percentage",
    "PAINT_TOUCH_PTS": "Paint Touch Points",
    "PAINT_TOUCH_PTS_PCT": "Paint Touch Points Percentage",
    "PAINT_TOUCH_PASSES": "Paint Touch Passes",
    "PAINT_TOUCH_PASSES_PCT": "Paint Touch Passes Percentage",
    "PAINT_TOUCH_PASS_PCT": "Paint Touch Pass Percentage",
    "PAINT_TOUCH_AST": "Paint Touch Assists",
    "PAINT_TOUCH_AST_PCT": "Paint Touch Percent of Team's Assists",
    "PAINT_TOUCH_TOV": "Paint Touch Turnovers",
    "PAINT_TOUCH_TOV_PCT": "Paint Touch Percent of Team's Turnovers",
    "PAINT_TOUCH_FOULS": "Paint Touch Fouls",
    "PAINT_TOUCH_FOULS_PCT": "Paint Touch Fouls Percentage",
    "PAINT_TOUCH_PF": "Paint Touch Personal Fouls",
    "PAINT_TOUCH_PF_PCT": "Paint Touch Percent of Team's Personal Fouls",
    # Passing
    "PASSES_MADE": "Passes Made",
    "PASSES_RECEIVED": "Passes Received",
    "PASS": "Pass",
    "PASS_PCT": "Pass Percentage",
    "SECONDARY_AST": "Secondary Assists",
    "POTENTIAL_AST": "Potential Assists",
    "AST_POINTS_CREATED": "Assist Points Created",
    "AST_ADJ": "Adjusted Assists",
    "AST_TO_PASS_PCT": "Assist to Pass Percentage",
    "AST_TO_PASS_PCT_ADJ": "Adjusted Assist to Pass Percentage",
    # Rebounding
    "REB_CONTEST": "Rebounds Contested",
    "REB_CONTESTED": "Contested Rebounds",
    "REB_CONTEST_PCT": "Contested Rebound Percentage",
    "REB_CHANCES": "Rebound Chances",
    "REB_CHANCE_PCT": "Rebound Chance Percentage",
    "REB_CHANCE_DEFER": "Rebound Chances Deferred",
    "DEFERRED_REB_CHANCES": "Deferred Rebound Chances",
    "REB_CHANCE_PCT_ADJ": "Adjusted Rebound Chance Percentage",
    "AVG_REB": "Average Rebound",
    "AVG_REB_DISTANCE": "Average Rebound Distance",
    "OREB_CONTEST": "Offensive Rebounds Contested",
    "OREB_CONTESTED": "Contested Offensive Rebounds",
    "OREB_CONTEST_PCT": "Contested Offensive Rebound Percentage",
    "OREB_CHANCES": "Offensive Rebound Chances",
    "CHANCES": "Offensive Rebound Chances",
    "OREB_CHANCE_PCT": "Offensive Rebound Chance Percentage",
    "CHANCE_PCT": "Offensive Rebound Chance Percentage",
    "OREB_CHANCE_DEFER": "Offensive Rebound Chances Deferred",
    "DEFERRED_OREB_CHANCES": "Deferred Offensive Rebound Chances",
    "OREB_CHANCE_PCT_ADJ": "Adjusted Offensive Rebound Chance Percentage",
    "ADJUSTED_OREB_CHANCE_PCT": "Adjusted Offensive Rebound Chance Percentage",
    "AVG_OREB": "Average Offensive Rebound",
    "OREB_DISTANCE": "Average Offensive Rebound Distance",
    "DREB_CONTEST": "Defensive Rebounds Contested",
    "DREB_CONTESTED": "Contested Defensive Rebounds",
    "CONTESTED": "Contested Defensive Rebounds",
    "DREB_CONTEST_PCT": "Contested Defensive Rebound Percentage",
    "DREB_CHANCES": "Defensive Rebound Chances",
    "DREB_CHANCE_PCT": "Defensive Rebound Chance Percentage",
    "DREB_CHANCE_DEFER": "Defensive Rebound Chances Deferred",
    "DEFERRED_DREB_CHANCES": "Deferred Defensive Rebound Chances",
    "DEFERRED": "Deferred Defensive Rebound Chances",
    "DREB_CHANCE_PCT_ADJ": "Adjusted Defensive Rebound Chance Percentage",
    "ADJUSTED_DREB_CHANCE_PCT": "Adjusted Defensive Rebound Chance Percentage",
    "ADJUSTED": "Adjusted Defensive Rebound Chance Percentage",
    "AVG_DREB": "Average Defensive Rebound",
    "DREB_DISTANCE": "Average Defensive Rebound Distance",
    "DISTANCE": "Average Defensive Rebound Distance",
    # Speed and Distance
    "DIST_FEET": "Distance Feet",
    "DIST_MILES": "Distance Miles",
    "DIST_MILES_OFF": "Distance Miles Offense",
    "DIST_MILES_DEF": "Distance Miles Defense",
    "AVG_SPEED": "Average Speed",
    "AVG_SPEED_OFF": "Average Speed Offense",
    "AVG_SPEED_DEF": "Average Speed Defense",
    "EFF_FG_PCT": "Effective Field Goal Percentage",
    # Shot Dashboard
    "FGA_FREQUENCY": "Field Goal Attempt Frequency",
    "FG2A_FREQUENCY": "2 Point Field Goal Attempt Frequency",
    "FG3A_FREQUENCY": "3 Point Field Goal Attempt Frequency",
    "G": "Games",
    "FREQ_WHOLE_NUM": "Frequency Whole Number",
    "D_FGM": "Defended Field Goals Made",
    "D_FGA": "Defended Field Goals Attempted",
    "D_FG_PCT": "Defended Field Goal Percentage",
    "NORMAL_FG_PCT": "Normal Field Goal Percentage",
    "NS_FG_PCT": "No Screen Field Goal Percentage",
    "NS_FG2_PCT": "No Screen 2 Point Field Goal Percentage",
    "NS_FG3_PCT": "No Screen 3 Point Field Goal Percentage",
    "NS_LT_06_PCT": "No Screen Less Than 0.6 ft. Field Goal Percentage",
    "NS_LT_10_PCT": "No Screen Less Than 10 ft. Field Goal Percentage",
    "NS_GT_15_PCT": "No Screen Greater Than 15 ft. Field Goal Percentage",
    "DFGM": "Defended Field Goals Made",
    "DFGA": "Defended Field Goals Attempted",
    "DFG_PCT": "Field Goals Defended at Rim Percent",
    # Hustle Statistics
    "BOX_OUTS": "Box Outs",
    "OFF_BOXOUTS": "Offensive Box Outs",
    "DEF_BOXOUTS": "Defensive Box Outs",
    "PCT_BOX_OUTS_OFF": "Percent of Box Outs (Offensive)",
    "PCT_BOX_OUTS_DEF": "Percent of Box Outs (Defensive)",
    "TEAM_REB_ON_BOX_OUTS": "Team Rebounds on Box Outs",
    "PLAYER_REB_ON_BOX_OUTS": "Player Rebounds on Box Outs",
    "PCT_TEAM_REB_WHEN_BOX_OUT": "Percent of Team Rebounds When Box Out",
    "PCT_PLAYER_REB_WHEN_BOX_OUT": "Percent of Player Rebounds When Box Out",
    "SCREEN_ASSISTS": "Screen Assists",
    "SCREEN_AST_PTS": "Screen Assist Points",
    "DEFLECTIONS": "Deflections",
    "OFF_LOOSE_BALLS_RECOVERED": "Offensive Loose Balls Recovered",
    "DEF_LOOSE_BALLS_RECOVERED": "Defensive Loose Balls Recovered",
    "LOOSE_BALLS_RECOVERED": "Total Loose Balls Recovered",
    "PCT_LOOSE_BALLS_RECOVERED_OFF": ("Percent of Loose Balls Recovered (Offensive)"),
    "PCT_LOOSE_BALLS_RECOVERED_DEF": ("Percent of Loose Balls Recovered (Defensive)"),
    "CHARGES_DRAWN": "Charges Drawn",
    "CONTESTED_SHOTS_2PT": "Contested Shots (2 Point)",
    "CONTESTED_SHOTS_3PT": "Contested Shots (3 Point)",
    "CONTESTED_SHOTS": "Total Contested Shots",
    # Miscellaneous
    "W_PCT": "Win Percentage",
    "FTA_RATE": "Free Throw Attempt Rate",
    "FP": "Fantasy Points",
    "DD2": "Double Doubles",
    "TD3": "Triple Doubles",
    # Advanced Box Score Fields
    "MATCHUP": "Matchup",
    "GDATE": "Game Date",
    "WIN_LOSE": "Win/Loss",
    # Frequency Statistics
    "TWO_P_FG_FREQ_PCT": "2-Point Field Goal Frequency",
    "THREE_P_FG_FREQ_PCT": "3-Point Field Goal Frequency",
    # Defended Field Goals (context-specific)
    "DFGM_TWO_PT": "Defended 2 Point Field Goals Made",
    "DFGA_TWO_PT": "Defended 2 Point Field Goals Attempted",
    "DFG_PCT_TWO_PT": "Defended 2 Point Field Goal Percentage",
    "DFGM_THREE_PT": "Defended 3 Point Field Goals Made",
    "DFGA_THREE_PT": "Defended 3 Point Field Goals Attempted",
    "DFG_PCT_THREE_PT": "Defended 3 Point Field Goal Percentage",
    # Percentage Difference
    "DIFF_PCT": "Percentage Points Different",
    # Dunk Statistics
    "DUNK_SCORE": "Dunk Score",
    "JMP": "Jump Subscore",
    "PWR": "Power Subscore",
    "STYL": "Style Subscore",
    "DEF": "Defensive Contest Subscore",
    "VERT": "Player Vertical Leap Height (in)",
    "HANG": "Player Hangtime (s)",
    "DIST": "Player Take-off Distance (ft)",
    "HAND": "Player Dunk Hand",
    "HGT": "Maximum Ball Height (ft)",
    "SPD": "Ball Speed through Rim (mph)",
    "RB": "Reach Back (ft)",
    "TIP": "Tip-Dunk",
    "OOP": "Alley-Oop",
}
TEAMS_GLOSSARY = {
    # Estadísticas Básicas Tradicionales
    "GP": "Partidos Jugados",
    "W": "Victorias",
    "L": "Derrotas",
    "WIN%": "Porcentaje de Victorias",
    "W_PCT": "Porcentaje de Victorias",
    "MIN": "Minutos Jugados",
    "PTS": "Puntos",
    "FGM": "Tiros de Campo Anotados",
    "FGA": "Tiros de Campo Intentados",
    "FG%": "Porcentaje de Tiros de Campo",
    "FG_PCT": "Porcentaje de Tiros de Campo",
    "THREE_P_M": "Tiros de Campo de Tres Puntos Anotados",
    "FG3M": "Tiros de Campo de Tres Puntos Anotados",
    "THREE_P_A": "Tiros de Campo de Tres Puntos Intentados",
    "FG3A": "Tiros de Campo de Tres Puntos Intentados",
    "THREE_P_PCT": "Porcentaje de Tiros de Campo de Tres Puntos",
    "FG3_PCT": "Porcentaje de Tiros de Campo de Tres Puntos",
    "FTM": "Tiros Libres Anotados",
    "FTA": "Tiros Libres Intentados",
    "FT%": "Porcentaje de Tiros Libres",
    "FT_PCT": "Porcentaje de Tiros Libres",
    "OREB": "Rebotes Ofensivos",
    "DREB": "Rebotes Defensivos",
    "REB": "Rebotes",
    "AST": "Asistencias",
    "TOV": "Pérdidas de Balón",
    "STL": "Robos",
    "BLK": "Tapones",
    "BLKA": "Tapones Recibidos",
    "PF": "Faltas Personales",
    "PFD": "Faltas Personales Provocadas",
    "PLUS_MINUS": "Más/Menos",
    # Estadísticas Avanzadas
    "OFFRTG": "Clasificación Ofensiva",
    "OFF_RATING": "Clasificación Ofensiva",
    "DEFRTG": "Clasificación Defensiva",
    "DEF_RATING": "Clasificación Defensiva",
    "DEF RTG": "Clasificación Defensiva",
    "NETRTG": "Clasificación Neta",
    "NET_RATING": "Clasificación Neta",
    "AST%": "Porcentaje de Asistencias",
    "AST_PCT": "Porcentaje de Asistencias",
    "AST/TO": "Ratio de Asistencias por Pérdida de Balón",
    "AST_TO": "Ratio de Asistencias por Pérdida de Balón",
    "AST RATIO": "Ratio de Asistencias",
    "AST_RATIO": "Ratio de Asistencias",
    "OREB%": "Porcentaje de Rebotes Ofensivos",
    "OREB_PCT": "Porcentaje de Rebotes Ofensivos",
    "DREB%": "Porcentaje de Rebotes Defensivos",
    "DREB_PCT": "Porcentaje de Rebotes Defensivos",
    "REB%": "Porcentaje de Rebotes",
    "REB_PCT": "Porcentaje de Rebotes",
    "TOV%": "Ratio de Pérdidas de Balón",
    "TM_TOV_PCT": "Ratio de Pérdidas de Balón",
    "TO_RATIO": "Ratio de Pérdidas de Balón",
    "EFG%": "Porcentaje Efectivo de Tiros de Campo",
    "EFG_PCT": "Porcentaje Efectivo de Tiros de Campo",
    "TS%": "Porcentaje Real de Tiros",
    "TS_PCT": "Porcentaje Real de Tiros",
    "PACE": "Ritmo de Juego",
    "PIE": "Estimación de Impacto del Jugador",
    "POSS": "Posesiones",
    # Estadísticas Misceláneas
    "OFF TO": "Puntos Tras Pérdidas de Balón",
    "OFF_TO": "Puntos Tras Pérdidas de Balón",
    "PTS_OFF_TOV": "Puntos Tras Pérdidas de Balón",
    "TWO_P_ND_PTS": "Puntos de Segunda Oportunidad",
    "TWO_P_ND_PTS_ALT": "Puntos de Segunda Oportunidad",
    "PTS_2ND_CHANCE": "Puntos de Segunda Oportunidad",
    "FBPS": "Puntos al Contraataque",
    "PTS_FB": "Puntos al Contraataque",
    "PITP": "Puntos en la Zona Pintada",
    "PTS_PAINT": "Puntos en la Zona Pintada",
    # Estadísticas del Oponente
    "OPP PTS": "Puntos del Oponente",
    "OPP_PTS": "Puntos del Oponente",
    "OPP OFF TO": "Puntos del Oponente Tras Pérdidas de Balón",
    "OPP_OFF_TO": "Puntos del Oponente Tras Pérdidas de Balón",
    "OPP_PTS_OFF_TOV": "Puntos del Oponente Tras Pérdidas de Balón",
    "OPP_TWO_P_ND_PTS": "Puntos de Segunda Oportunidad del Oponente",
    "OPP_TWO_P_ND_PTS_ALT": "Puntos de Segunda Oportunidad del Oponente",
    "OPP_PTS_2ND_CHANCE": "Puntos de Segunda Oportunidad del Oponente",
    "OPP FBPS": "Puntos al Contraataque del Oponente",
    "OPP_FBPS": "Puntos al Contraataque del Oponente",
    "OPP_PTS_FB": "Puntos al Contraataque del Oponente",
    "OPP PITP": "Puntos en la Zona Pintada del Oponente",
    "OPP_PITP": "Puntos en la Zona Pintada del Oponente",
    "OPP_PTS_PAINT": "Puntos en la Zona Pintada del Oponente",
    "OPP_FGM": "Tiros de Campo Anotados por el Oponente",
    "OPP_FGA": "Tiros de Campo Intentados por el Oponente",
    "OPP_FG%": "Porcentaje de Tiros de Campo del Oponente",
    "OPP_FG_PCT": "Porcentaje de Tiros de Campo del Oponente",
    "OPP_3PM": "Tiros de Campo de 3 Puntos Anotados por el Oponente",
    "OPP_FG3M": "Tiros de Campo de 3 Puntos Anotados por el Oponente",
    "OPP_3PA": "Tiros de Campo de 3 Puntos Intentados por el Oponente",
    "OPP_FG3A": "Tiros de Campo de 3 Puntos Intentados por el Oponente",
    "OPP_3P%": "Porcentaje de Tiros de Campo de 3 Puntos del Oponente",
    "OPP_FG3_PCT": "Porcentaje de Tiros de Campo de 3 Puntos del Oponente",
    "OPP_FTM": "Tiros Libres Anotados por el Oponente",
    "OPP_FTA": "Tiros Libres Intentados por el Oponente",
    "OPP_FT%": "Porcentaje de Tiros Libres del Oponente",
    "OPP_FT_PCT": "Porcentaje de Tiros Libres del Oponente",
    "OPP_OREB": "Rebotes Ofensivos del Oponente",
    "OPP_DREB": "Rebotes Defensivos del Oponente",
    "OPP_REB": "Rebotes del Oponente",
    "OPP_AST": "Asistencias del Oponente",
    "OPP_TOV": "Pérdidas de Balón del Oponente",
    "OPP_STL": "Robos del Oponente",
    "OPP_BLK": "Tapones del Oponente",
    "OPP_BLKA": "Tiros de Campo Bloqueados Intentados por el Oponente",
    "OPP_PF": "Faltas Personales del Oponente",
    "OPP_PFD": "Faltas Personales Recibidas por el Oponente",
    # Four Factors
    "FTA RATE": "Tasa de Intentos de Tiros Libres",
    "FTA_RATE": "Tasa de Intentos de Tiros Libres",
    "OPP FTA RATE": "Tasa de Intentos de Tiros Libres del Oponente",
    "OPP_FTA_RATE": "Tasa de Intentos de Tiros Libres del Oponente",
    "OPP EFG%": "Porcentaje Efectivo de Tiros de Campo del Oponente",
    "OPP_EFG_PCT": "Porcentaje Efectivo de Tiros de Campo del Oponente",
    "OPP TOV%": "Porcentaje de Ratio de Pérdidas de Balón del Oponente",
    "OPP_TOV_PCT": "Porcentaje de Ratio de Pérdidas de Balón del Oponente",
    "OPP OREB%": "Porcentaje de Rebotes Ofensivos del Oponente",
    "OPP_OREB_PCT": "Porcentaje de Rebotes Ofensivos del Oponente",
    # Estadísticas de Anotación
    "TWO_P_PT_PCT_FGA": "Porcentaje de Intentos de Tiros de Campo (2 Puntos)",
    "PCT_FGA_2PT": "Porcentaje de Intentos de Tiros de Campo (2 Puntos)",
    "THREE_P_PT_PCT_FGA": "Porcentaje de Intentos de Tiros de Campo (3 Puntos)",
    "PCT_FGA_3PT": "Porcentaje de Intentos de Tiros de Campo (3 Puntos)",
    "TWO_P_PT_PCT_PTS": "Porcentaje de Puntos (2 Puntos)",
    "PCT_PTS_2PT": "Porcentaje de Puntos (2 Puntos)",
    "TWO_P_PT_MR_PCT_PTS": "Porcentaje de Puntos (Media Distancia)",
    "PCT_PTS_2PT_MR": "Porcentaje de Puntos (Media Distancia)",
    "THREE_P_PT_PCT_PTS": "Porcentaje de Puntos (3 Puntos)",
    "PCT_PTS_3PT": "Porcentaje de Puntos (3 Puntos)",
    "FBPS_PCT_PTS": "Porcentaje de Puntos (Puntos de Contraataque)",
    "PCT_PTS_FB": "Porcentaje de Puntos (Puntos de Contraataque)",
    "FT_PCT_PTS": "Porcentaje de Puntos (Tiros Libres)",
    "PCT_PTS_FT": "Porcentaje de Puntos (Tiros Libres)",
    "OFFTO_PCT_PTS": "Porcentaje de Puntos (Tras Pérdidas de Balón)",
    "PCT_PTS_OFF_TOV": "Porcentaje de Puntos (Tras Pérdidas de Balón)",
    "PITP_PCT_PTS": "Porcentaje de Puntos (Puntos en la Pintura)",
    "PCT_PTS_PAINT": "Porcentaje de Puntos (Puntos en la Pintura)",
    "TWO_P_FGM": "Tiros de Campo de 2 Puntos Anotados",
    "FG2M": "Tiros de Campo de 2 Puntos Anotados",
    "PCT_AST_TWO_P_FGM": "Porcentaje de Tiros de Campo de 2 Puntos Anotados Asistidos",
    "PCT_AST_2PM": "Porcentaje de Tiros de Campo de 2 Puntos Anotados Asistidos",
    "PCT_UAST_TWO_P_FGM": "Porcentaje de Tiros de Campo de 2 Puntos Anotados Sin Asistencia",
    "PCT_UAST_2PM": "Porcentaje de Tiros de Campo de 2 Puntos Anotados Sin Asistencia",
    "THREE_P_FGM": "Tiros de Campo de 3 Puntos Anotados",
    "FG3M": "Tiros de Campo de 3 Puntos Anotados",
    "PCT_AST_THREE_P_FGM": "Porcentaje de Tiros de Campo de 3 Puntos Anotados Asistidos",
    "PCT_AST_3PM": "Porcentaje de Tiros de Campo de 3 Puntos Anotados Asistidos",
    "PCT_UAST_THREE_P_FGM": "Porcentaje de Tiros de Campo de 3 Puntos Anotados Sin Asistencia",
    "PCT_UAST_3PM": "Porcentaje de Tiros de Campo de 3 Puntos Anotados Sin Asistencia",
    "PCT_AST_FGM": "Porcentaje de Tiros de Campo Anotados Asistidos",
    "PCT_AST_FGM_ALT": "Porcentaje de Tiros de Campo Anotados Asistidos",
    "PCT_UAST_FGM": "Porcentaje de Tiros de Campo Anotados Sin Asistencia",
    "PCT_UAST_FGM_ALT": "Porcentaje de Tiros de Campo Anotados Sin Asistencia",
    # Estadísticas de Defensa
    "OPP PTS OFF TOV": "Puntos del Oponente Tras Pérdidas de Balón",
    "OPP_PTS_OFF_TOV": "Puntos del Oponente Tras Pérdidas de Balón",
    "OFF TOV": "Puntos del Oponente Tras Pérdidas de Balón",
    "TWO_P_ND_CHANCE": "Puntos de Segunda Oportunidad del Oponente",
    "OPP_2ND_CHANCE": "Puntos de Segunda Oportunidad del Oponente",
    "FB": "Puntos al Contraataque del Oponente",
    "OPP_FB": "Puntos al Contraataque del Oponente",
    "PAINT": "Puntos en la Zona Pintada del Oponente",
    "OPP_PAINT": "Puntos en la Zona Pintada del Oponente",
    # Estadísticas Estimadas
    "EST_OFF_RATING": "Clasificación Ofensiva Estimada",
    "EST_DEF_RATING": "Clasificación Defensiva Estimada",
    "EST_NET_RATING": "Clasificación Neta Estimada",
    "EST_AST_RATIO": "Ratio de Asistencias Estimado",
    "EST_OREB_PCT": "Porcentaje de Rebotes Ofensivos Estimado",
    "EST_DREB_PCT": "Porcentaje de Rebotes Defensivos Estimado",
    "EST_REB_PCT": "Porcentaje de Rebotes Estimado",
    "EST_TOV_PCT": "Ratio de Pérdidas de Balón Estimado",
    "EST_PACE": "Ritmo de Juego Estimado",
    # Violaciones
    "OFF_GLTND": "Goaltending Ofensivo",
    "OFF_GOALTENDING": "Goaltending Ofensivo",
    "OFF_FOUL": "Falta Ofensiva",
    "DEF_GLTND": "Goaltending Defensivo",
    "DEF_GOALTENDING": "Goaltending Defensivo",
}
