"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vz+du974h9+nba#ix&ggwst-sqs8cgsd%@1txg^sht#d_^fmlt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Unfold django theme
    "unfold",
    "crispy_forms",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    # Project apps
    "data",
    "dashboard",
    "roster",
    # Project commands
    "project_commands",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "postgres",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# Static files configuration for development
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Evolveme
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "")

ADMIN_GROUPS = os.getenv("ADMIN_GROUPS", "").split(",")
ROLE_PERMISSIONS = {
    "owner": [],
}

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]
CRISPY_TEMPLATE_PACK = "unfold_crispy"

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Cache configuration con Redis
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://redis:6379/1",
    }
}

# Session configuration
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Celery Configuration
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Static files
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "NBA Data Manager",
    "SITE_HEADER": "NBA Data Manager",
    "SITE_SUBHEADER": "Panel de Administración",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/ico.png",
        "dark": lambda request: "/static/ico.png",
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: "/static/ico.png",
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "BORDER_RADIUS": "8px",
    "THEME": None,  # Permite cambio de tema (claro/oscuro)
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            # Colores azules más vibrantes
            "50": "oklch(98% .02 240)",  # Azul muy claro
            "100": "oklch(95% .04 240)",  # Azul claro
            "200": "oklch(90% .08 240)",  # Azul medio-claro
            "300": "oklch(82% .15 240)",  # Azul medio
            "400": "oklch(70% .25 240)",  # Azul
            "500": "oklch(60% .3 240)",  # Azul principal
            "600": "oklch(50% .3 240)",  # Azul oscuro
            "700": "oklch(42% .25 240)",  # Azul más oscuro
            "800": "oklch(35% .2 240)",  # Azul muy oscuro
            "900": "oklch(28% .15 240)",  # Azul casi negro
            "950": "oklch(20% .1 240)",  # Azul negro
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
}

NBA_TEAMS_INFO = {
    "Atlanta Hawks": ["ATL", 1610612737, "East", "Southeast"],
    "Boston Celtics": ["BOS", 1610612738, "East", "Atlantic"],
    "Brooklyn Nets": ["BKN", 1610612751, "East", "Atlantic"],
    "Charlotte Hornets": ["CHA", 1610612766, "East", "Southeast"],
    "Chicago Bulls": ["CHI", 1610612741, "East", "Central"],
    "Cleveland Cavaliers": ["CLE", 1610612739, "East", "Central"],
    "Dallas Mavericks": ["DAL", 1610612742, "West", "Southwest"],
    "Denver Nuggets": ["DEN", 1610612743, "West", "Northwest"],
    "Detroit Pistons": ["DET", 1610612765, "East", "Central"],
    "Golden State Warriors": ["GSW", 1610612744, "West", "Pacific"],
    "Houston Rockets": ["HOU", 1610612745, "West", "Southwest"],
    "Indiana Pacers": ["IND", 1610612754, "East", "Central"],
    "Los Angeles Clippers": ["LAC", 1610612746, "West", "Pacific"],
    "Los Angeles Lakers": ["LAL", 1610612747, "West", "Pacific"],
    "Memphis Grizzlies": ["MEM", 1610612763, "West", "Southwest"],
    "Miami Heat": ["MIA", 1610612748, "East", "Southeast"],
    "Milwaukee Bucks": ["MIL", 1610612749, "East", "Central"],
    "Minnesota Timberwolves": ["MIN", 1610612750, "West", "Northwest"],
    "New Orleans Pelicans": ["NOP", 1610612740, "West", "Southwest"],
    "New York Knicks": ["NYK", 1610612752, "East", "Atlantic"],
    "Oklahoma City Thunder": ["OKC", 1610612760, "West", "Northwest"],
    "Orlando Magic": ["ORL", 1610612753, "East", "Southeast"],
    "Philadelphia 76ers": ["PHI", 1610612755, "East", "Atlantic"],
    "Phoenix Suns": ["PHX", 1610612756, "West", "Pacific"],
    "Portland Trail Blazers": ["POR", 1610612757, "West", "Northwest"],
    "Sacramento Kings": ["SAC", 1610612758, "West", "Pacific"],
    "San Antonio Spurs": ["SAS", 1610612759, "West", "Southwest"],
    "Toronto Raptors": ["TOR", 1610612761, "East", "Atlantic"],
    "Utah Jazz": ["UTA", 1610612762, "West", "Northwest"],
    "Washington Wizards": ["WAS", 1610612764, "East", "Southeast"],
}
