# Generated by Django 5.2 on 2026-01-03 21:13

import django.core.validators
import ia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('algorithm_type', models.CharField(blank=True, choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('svm', 'SVM'), ('naive_bayes', 'Naive Bayes'), ('gradient_boosting', 'Gradient Boosting'), ('linear_regression', 'Linear Regression'), ('ridge_regression', 'Ridge Regression'), ('lasso_regression', 'Lasso Regression'), ('mlp', 'MLP (Neural Network)'), ('cnn', 'CNN'), ('rnn', 'RNN'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('voting_classifier', 'Voting Classifier'), ('stacking_classifier', 'Stacking Classifier'), ('bagging_classifier', 'Bagging Classifier'), ('adaboost', 'AdaBoost'), ('elo', 'ELO Rating'), ('glicko', 'Glicko Rating'), ('trueskill', 'TrueSkill Rating')], max_length=50)),
                ('problem_type', models.CharField(blank=True, choices=[('classification', 'Classification'), ('binary_classification', 'Binary Classification'), ('multiclass_classification', 'Multiclass Classification'), ('regression', 'Regression'), ('rating', 'Rating System')], max_length=50)),
                ('model_file', models.FileField(blank=True, help_text='Archivo .pkl del modelo entrenado', null=True, upload_to=ia.models.model_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pkl'])])),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Modelo activo para predicciones')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Métricas de evaluación del modelo (accuracy, mse, r2, etc.)')),
                ('training_data_info', models.JSONField(blank=True, default=dict, help_text='Información sobre los datos de entrenamiento (tamaño, features, etc.)')),
                ('hyperparameters', models.JSONField(blank=True, default=dict, help_text='Hiperparámetros del modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prediction Model',
                'verbose_name_plural': 'Prediction Models',
                'ordering': ['-created_at'],
            },
        ),
    ]
