# Generated by Django 5.2.13 on 2026-04-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='URL base del servidor Ollama, p.ej. http://localhost:11434')),
                ('enabled', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor Ollama',
                'verbose_name_plural': 'Servidores Ollama',
            },
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('content', models.TextField(verbose_name='Contenido del prompt')),
                ('is_active', models.BooleanField(default=False, help_text='Solo un prompt puede estar activo. Al activar este se desactivan los demás.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt de sistema',
                'verbose_name_plural': 'Prompts de sistema',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de chat',
                'verbose_name_plural': 'Sesiones de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.chatsession')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OllamaModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=0.9)),
                ('max_tokens', models.PositiveIntegerField(default=512)),
                ('alias', models.CharField(help_text='Nombre lógico en la app', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('ollama_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última comprobación')),
                ('ollama_installed', models.BooleanField(blank=True, null=True, verbose_name='Instalado en Ollama')),
                ('ollama_local_digest', models.CharField(blank=True, max_length=128, verbose_name='Digest local')),
                ('ollama_registry_digest', models.CharField(blank=True, max_length=128, verbose_name='Digest en registry')),
                ('ollama_up_to_date', models.BooleanField(blank=True, null=True, verbose_name='Al día')),
                ('ollama_sync_detail', models.CharField(blank=True, max_length=500, verbose_name='Detalle sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ia.ollamaserver')),
            ],
            options={
                'verbose_name': 'Modelo Ollama',
                'verbose_name_plural': 'Modelos Ollama',
                'unique_together': {('server', 'model_name')},
            },
        ),
    ]
