# Generated by Django 5.1.5 on 2025-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL de la página web', max_length=500)),
                ('category', models.CharField(help_text='Categoría de la página web', max_length=100)),
                ('season', models.CharField(help_text='Temporada de la página web', max_length=10)),
                ('season_type', models.CharField(help_text='Tipo de temporada de la página web', max_length=20)),
                ('status', models.CharField(help_text='Estado de la página web', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True, help_text='Error de la página web', null=True)),
            ],
            options={
                'verbose_name': 'Scrapper Log',
                'verbose_name_plural': 'Scrapper Logs',
            },
        ),
    ]
