# Generated by Django 5.1.5 on 2025-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapper_name', models.CharField(choices=[('advanced_boxscore_scraper', 'Advanced Boxscore Scraper'), ('box_outs_scraper', 'Box Outs Scraper'), ('boxscore_scraper', 'Boxscore Scraper'), ('catch_shoot_scraper', 'Catch & Shoot Scraper'), ('clutch_scraper', 'Clutch Scraper'), ('defense_dashboard_scraper', 'Defense Dashboard Scraper'), ('defensive_impact_scraper', 'Defensive Impact Scraper'), ('defensive_rebounding_scraper', 'Defensive Rebounding Scraper'), ('drives_scraper', 'Drives Scraper'), ('elbow_touch_scraper', 'Elbow Touch Scraper'), ('hustle_scraper', 'Hustle Scraper'), ('offensive_rebounding_scraper', 'Offensive Rebounding Scraper'), ('opponent_shooting_scraper', 'Opponent Shooting Scraper'), ('paint_touch_scraper', 'Paint Touch Scraper'), ('passing_scraper', 'Passing Scraper'), ('playtipe_scraper', 'Playtipe Scraper'), ('post_ups_scraper', 'Post Ups Scraper'), ('pull_up_shooting_scraper', 'Pull Up Shooting Scraper'), ('rebounding_scraper', 'Rebounding Scraper'), ('shooting_efficiency_scraper', 'Shooting Efficiency Scraper'), ('shooting_scraper', 'Shooting Scraper'), ('shot_dashboard_scraper', 'Shot Dashboard Scraper'), ('speed_distance_scraper', 'Speed & Distance Scraper'), ('touches_scraper', 'Touches Scraper')], help_text='Nombre del scraper', max_length=100)),
                ('last_execution', models.DateTimeField(auto_now_add=True)),
                ('last_link_scraped', models.URLField(blank=True, help_text='Último enlace scrapeado', max_length=500, null=True)),
                ('is_running', models.BooleanField(default=False, help_text='Indica si el scraper está en ejecución')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scrapper Status',
                'verbose_name_plural': 'Scrapper Status',
            },
        ),
    ]
