# Generated by Django 5.1.5 on 2025-10-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_scrapperstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapperstatus',
            name='updated_at',
        ),
    ]
