# Generated by Django 5.2 on 2026-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupsadvanced',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AddField(
            model_name='lineupsadvanced',
            name='team_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura del Equipo'),
        ),
        migrations.AddField(
            model_name='lineupsfourfactors',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AddField(
            model_name='lineupsfourfactors',
            name='team_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura del Equipo'),
        ),
        migrations.AddField(
            model_name='lineupsmisc',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AddField(
            model_name='lineupsmisc',
            name='team_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura del Equipo'),
        ),
        migrations.AddField(
            model_name='lineupsopponent',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AddField(
            model_name='lineupsopponent',
            name='team_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura del Equipo'),
        ),
        migrations.AddField(
            model_name='lineupsscoring',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AddField(
            model_name='lineupsscoring',
            name='team_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura del Equipo'),
        ),
        migrations.AddField(
            model_name='lineupstraditional',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AddField(
            model_name='lineupstraditional',
            name='team_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura del Equipo'),
        ),
        migrations.AlterField(
            model_name='lineupsadvanced',
            name='min',
            field=models.FloatField(blank=True, default=0.0, help_text='Minutos Jugados', null=True, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='lineupsfourfactors',
            name='min',
            field=models.FloatField(blank=True, default=0.0, help_text='Minutos Jugados', null=True, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='min',
            field=models.FloatField(blank=True, default=0.0, help_text='Minutos Jugados', null=True, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='opp_pts_2nd_chance',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos de Segunda Oportunidad del Oponente', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='opp_pts_fb',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos al Contraataque del Oponente', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='opp_pts_off_tov',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos del Oponente Tras Pérdidas de Balón', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='opp_pts_paint',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos en la Zona Pintada del Oponente', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='pts_2nd_chance',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos de Segunda Oportunidad', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='pts_fb',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos al Contraataque', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='pts_off_tov',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos Tras Pérdidas de Balón', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsmisc',
            name='pts_paint',
            field=models.FloatField(blank=True, default=0.0, help_text='Puntos en la Zona Pintada', null=True),
        ),
        migrations.AlterField(
            model_name='lineupsopponent',
            name='min',
            field=models.FloatField(blank=True, default=0.0, help_text='Minutos Jugados', null=True, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='lineupsscoring',
            name='min',
            field=models.FloatField(blank=True, default=0.0, help_text='Minutos Jugados', null=True, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='lineupstraditional',
            name='min',
            field=models.FloatField(blank=True, default=0.0, help_text='Minutos Jugados', null=True, verbose_name='Minutos'),
        ),
    ]
