# Generated by Django 5.2.13 on 2026-04-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0003_drop_all_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='LineupsAdvanced'),
                migrations.DeleteModel(name='LineupsFourFactors'),
                migrations.DeleteModel(name='LineupsMisc'),
                migrations.DeleteModel(name='LineupsOpponent'),
                migrations.DeleteModel(name='LineupsScoring'),
                migrations.DeleteModel(name='LineupsTraditional'),
            ],
        ),
    ]
