{
 "title": "Django",
 "tags": [
  "django",
  "nba",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total{status=~\"2..\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(django_http_responses_total{status=~\"3..\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(django_http_responses_total{status=~\"4..\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(django_http_responses_total{status=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "DB Query Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(django_db_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "DB Connection Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(django_db_connection_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(django_cache_hits_total[5m]) / (rate(django_cache_hits_total[5m]) + rate(django_cache_misses_total[5m]))",
     "legendFormat": "{{cache_backend}}"
    }
   ]
  },
  {
   "title": "Number of Requests by Processing Time, 1/1m",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(django_http_request_duration_seconds_bucket[1m])) by (le)"
    }
   ]
  },
  {
   "title": "Number of Responses by Size, 1/1m",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total[1m])) by (le)"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "99 quantile"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total{status=\"200\"}[5m]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(django_http_responses_total{status=\"204\"}[5m]))",
     "legendFormat": "204"
    },
    {
     "expr": "sum(rate(django_http_responses_total{status=\"301\"}[5m]))",
     "legendFormat": "301"
    },
    {
     "expr": "sum(rate(django_http_responses_total{status=\"302\"}[5m]))",
     "legendFormat": "302"
    },
    {
     "expr": "sum(rate(django_http_responses_total{status=\"404\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Top 20 Views by Response Time (> 1s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_request_duration_seconds_bucket{view!=\"\"}[5m])) by (le, view)) > 1",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Top Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (view) (rate(django_http_requests_total[5m])))"
    }
   ]
  }
 ]
}