# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gameplaybyplay",
            unique_together={
                (
                    "season",
                    "season_type",
                    "game_id",
                    "team_abb",
                    "period",
                    "min",
                    "score",
                    "player",
                    "action",
                )
            },
        ),
    ]
