# Generated by Django 5.2 on 2025-12-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(db_index=True, help_text='Identificador numérico único del equipo', verbose_name='ID del Equipo')),
                ('team_name', models.CharField(help_text='Nombre completo del equipo', max_length=100, verbose_name='Nombre del Equipo')),
                ('team_abb', models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BKN', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards')], help_text='Abreviación del equipo', max_length=10, verbose_name='Abreviación del Equipo')),
                ('team_conference', models.CharField(help_text='Conferencia del equipo', max_length=20, verbose_name='Conferencia del Equipo')),
                ('team_division', models.CharField(help_text='División del equipo', max_length=20, verbose_name='División del Equipo')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['team_name'],
                'indexes': [models.Index(fields=['team_name'], name='roster_team_team_na_68a0aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(db_index=True, help_text='Identificador numérico único del jugador', verbose_name='ID del Jugador')),
                ('player_name', models.CharField(help_text='Nombre completo del jugador', max_length=100, verbose_name='Nombre del Jugador')),
                ('player_abb', models.CharField(help_text='Abreviación del jugador', max_length=50, verbose_name='Abreviación del Jugador')),
                ('season', models.CharField(choices=[('2015-16', '2015-16'), ('2016-17', '2016-17'), ('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26')], help_text='Temporada del jugador (formato: YYYY-YY, ej: 2015-16)', max_length=10, verbose_name='Temporada')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.teams')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['player_name'],
                'indexes': [models.Index(fields=['player_name'], name='roster_play_player__2d6a12_idx')],
                'constraints': [models.UniqueConstraint(fields=('player_id', 'season', 'team'), name='unique_player_season_team')],
            },
        ),
    ]
