# Generated by Django 5.2 on 2025-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_abb',
            field=models.CharField(help_text='Abreviación del equipo', max_length=10, verbose_name='Abreviación del Equipo'),
        ),
    ]
