# Generated by Django 5.2.13 on 2026-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameFeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=64, verbose_name='GAME_ID')),
                ('market', models.CharField(db_index=True, default='base', max_length=32, verbose_name='Mercado (moneyline, totals, spread, props, in_game)')),
                ('features', models.JSONField(default=dict, verbose_name='Features (dict)')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de cómputo')),
                ('season', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='SEASON')),
                ('season_type', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='SEASON_TYPE')),
            ],
            options={
                'verbose_name': 'Game feature set',
                'verbose_name_plural': 'Game feature sets',
                'ordering': ['-computed_at', 'game_id'],
                'indexes': [models.Index(fields=['game_id', 'market'], name='features_ga_game_id_52a767_idx'), models.Index(fields=['season', 'season_type'], name='features_ga_season_a3b826_idx')],
                'unique_together': {('game_id', 'market')},
            },
        ),
        migrations.CreateModel(
            name='PlayerFeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(db_index=True, max_length=40, verbose_name='PLAYER_ID')),
                ('as_of_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de referencia')),
                ('context', models.CharField(default='all', max_length=32, verbose_name='Contexto (scoring/rebounding/playmaking/defense)')),
                ('features', models.JSONField(default=dict, verbose_name='Features (dict)')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de cómputo')),
                ('season', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='SEASON')),
            ],
            options={
                'verbose_name': 'Player feature set',
                'verbose_name_plural': 'Player feature sets',
                'ordering': ['-as_of_date', 'player_id'],
                'indexes': [models.Index(fields=['player_id', 'as_of_date'], name='features_pl_player__756fb6_idx'), models.Index(fields=['season', 'context'], name='features_pl_season_4e2e4d_idx')],
            },
        ),
    ]
