# Generated by Django 5.1.5 on 2025-10-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del partido')),
                ('game_id', models.CharField(help_text='Identificador único del partido', max_length=50, unique=True)),
                ('home_team', models.CharField(help_text='Equipo local', max_length=50)),
                ('away_team', models.CharField(help_text='Equipo visitante', max_length=50)),
                ('scraped', models.BooleanField(default=False, help_text='Indica si los datos de este partido ya han sido extraídos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-date', 'home_team'],
                'indexes': [models.Index(fields=['date'], name='source_game_date_4ec2b2_idx'), models.Index(fields=['game_id'], name='source_game_game_id_fac013_idx'), models.Index(fields=['home_team'], name='source_game_home_te_d24c93_idx'), models.Index(fields=['away_team'], name='source_game_away_te_4d3c5b_idx'), models.Index(fields=['scraped'], name='source_game_scraped_d25a2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Categoría de estadísticas (ej: boxscores-traditional, box-outs)', max_length=100)),
                ('season_type', models.CharField(help_text='Tipo de temporada (Pre+Season, Regular+Season, Playoffs, All+Star, PlayIn, IST)', max_length=20)),
                ('season', models.CharField(help_text='Temporada (ej: 2015-16, 2024-25)', max_length=10)),
                ('url', models.URLField(help_text='URL completa del enlace de NBA.com', max_length=500)),
                ('scraped', models.BooleanField(default=False, help_text='Indica si los datos de este enlace ya han sido extraídos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['category', '-season', 'season_type'],
                'indexes': [models.Index(fields=['category'], name='source_link_categor_b7f49f_idx'), models.Index(fields=['season_type'], name='source_link_season__5f6898_idx'), models.Index(fields=['season'], name='source_link_season_7d87b9_idx'), models.Index(fields=['scraped'], name='source_link_scraped_924cb0_idx'), models.Index(fields=['category', 'season_type', 'season'], name='source_link_categor_8f17c1_idx')],
                'unique_together': {('category', 'season_type', 'season')},
            },
        ),
    ]
