# Generated by Django 5.2 on 2026-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersboxscores',
            name='team_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID del Equipo'),
        ),
        migrations.AddField(
            model_name='playersboxscores',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='playersbios',
            name='college',
            field=models.CharField(blank=True, help_text='College', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playersbios',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playersbios',
            name='player_height_inches',
            field=models.CharField(blank=True, help_text='Altura ej. 6-10', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playersbios',
            name='player_weight',
            field=models.CharField(blank=True, help_text='Peso ej. 245', max_length=10, null=True),
        ),
    ]
